### ISSUE TITLE
Discussion on which family records should be included with different ancestor/descendant levels

### ISSUE THREAD

**Issue by Neriderc** [Neriderc/GVExport#101]
Currently if you select no ancestor or descendant generations, you will only get the starting individual(s) and no others.

If the user has selected "Siblings", "All relatives", "Anyone", should we include the family record? Follow the links keeping within the selected generation?

Should the family record with the parents be included in all cases? Or only if one of these options is selected?

As per discussion in #85, the last descendant generation does not have spouses because they are the records linked to the family record, and you'd need to go a further generation to get their family record with their spouse. Does something similar apply here, where the top record should just be parents? If no ancestor generations are included, does this mean there should not be a family record with their parents? Should the family record be included but not display the parents?

I'm keen to hear some thoughts on whether this is working right at the moment or if we should make some changes.

**Comment by hartenthaler** [comment]
> Currently if you select no ancestor or descendant generations, you will only get the starting individual(s) and no others.
This is only true in simple mode, not in combined mode.

I would prefer that the defined max generations are used in all cases
- if max ancestor and max descendent generations are set to 0, I would not like to see parents or children or their families. I would like to see partners (if the option "partner is selected") of the start persons and all the partners of partners if "all relatives" or "anyone" is selected. Including the partnership families of those partners (because these families are in generation 0).
- siblings are in the same generation (0), but their families are defined in the ancestor generation 1; so if max ancestor and max descendent generations are set to 0 and "siblings" is selected, I would expect to see no siblings. To see them I have to select max ancestor generation greater or equal 1.
-  if max ancestor generation is set to 0 and max descendent generations is set to 1, I would expect to see all children of the starting persons (and the corresponding partners if "partner" is selected); if "anyone" is selected I would expect to see all the partners of partners and all their children (step-children, step-step-children) and all the partners of the children (children-in-law and step-children-in-law) and all the parents of those partners of the children (and all families of those persons).

I would prefer to see in simple and combined mode the same persons and families (only the presentation should be different).

> If no ancestor generations are included, does this mean there should not be a family record with their parents? 
Yes. If max ancestor generation is 0 there should be no parent family. If max ancestor generation is 1 there are parent families but no grandparent families. 

> Should the family record be included but not display the parents?
No. The family record of parents (and their children) belongs to generation 1. It should be not visible. And the parents should be not shown, too. And even if "anyone" is selected no siblings, no parents should be visible. 

Maybe in general the option "siblings" is difficult and should be removed maybe (like you have already removed the option "cousins". What do you think to offer instead a new option: "(number of) steps" or "radius". One step is root - child or root - parent, one step is root - partner. Two steps are root - grandparent, root - grandchild, root - partner - partner. It has to be defined if root - (full-)sibling is one or two steps. This can be combined with "only related" or "anyone". My module "extended family" uses this approach to show for the root person (proband) all members of the extended family going one, two, three, ... steps in any direction. This approach would allow you to limit the number of persons in GVExport in a better way as it is now in the code of "any_option", where the number of persons explodes if you have more than two or three generations.

But why not use the possibility of the module "extended family" instead of reinventing the wheel? My module will offer the possibility to copy the members and families of the extended family to the clippings cart, and then you can visualize them with GVExport.

**Comment by Neriderc** [comment]
> > Currently if you select no ancestor or descendant generations, you will only get the starting individual(s) and no others.
> 
> This is only true in simple mode, not in combined mode.

I've played a bit more and to be honest, it's really inconsistent what you get when you enable/disable ancestor/descendant generations, or enable them but set to 0, and switch between combined and simple/decorated mode.

> I would prefer that the defined max generations are used in all cases
> 
>   if max ancestor and max descendent generations are set to 0, I would not like to see parents or children or their families. I would like to see partners (if the option "partner is selected") of the start persons and all the partners of partners if "all relatives" or "anyone" is selected. Including the partnership families of those partners (because these families are in generation 0).

How would this look on the diagram? Would the starting person have their family record with their partner showing (but no children), and then the spouse would have a family record with their other spouse and so on? This actually seems to happen if you disable ancestors and descendants rather than setting them to 0 (but not in combined mode). If this is what you meant, then perhaps we can be a bit more deliberate about which options cause this to show.

>    siblings are in the same generation (0), but their families are defined in the ancestor generation 1; so if max ancestor and max descendent generations are set to 0 and "siblings" is selected, I would expect to see no siblings. To see them I have to select max ancestor generation greater or equal 1.

> 
>    if max ancestor generation is set to 0 and max descendent generations is set to 1, I would expect to see all children of the starting persons (and the corresponding partners if "partner" is selected); if "anyone" is selected I would expect to see all the partners of partners and all their children (step-children, step-step-children) and all the partners of the children (children-in-law and step-children-in-law) and all the parents of those partners of the children (and all families of those persons).

There has been a previous discussion in #85 that the last descendant generation should have the children of the previous generation but not partners of these children because this generation does not have their family records included.

> I would prefer to see in simple and combined mode the same persons and families (only the presentation should be different).

Yes this makes sense.

> 
> Maybe in general the option "siblings" is difficult and should be removed maybe (like you have already removed the option "cousins". 

"Cousins" hasn't been removed, just renamed to "All relatives". The functionality is the same, it was renamed because it was adding individuals that were not cousins (nieces and nephews).

> What do you think to offer instead a new option: "(number of) steps" or "radius". One step is root - child or root - parent, one step is root - partner. Two steps are root - grandparent, root - grandchild, root - partner - partner. It has to be defined if root - (full-)sibling is one or two steps. This can be combined with "only related" or "anyone". My module "extended family" uses this approach to show for the root person (proband) all members of the extended family going one, two, three, ... steps in any direction. This approach would allow you to limit the number of persons in GVExport in a better way as it is now in the code of "any_option", where the number of persons explodes if you have more than two or three generations.
> 
> But why not use the possibility of the module "extended family" instead of reinventing the wheel? My module will offer the possibility to copy the members and families of the extended family to the clippings cart, and then you can visualize them with GVExport.

Yes as we've discussed before, it's best to keep the main UI simple and advanced users can use modules like yours in conjunction with the clippings cart to fine tune this if they wish. GVExport has claimed in the past that _GVExport's goal is to produce an "all in one tree" of every person in a family tree and their relationships._ This typically hasn't actually been possible because it stops at spouses of relatives and goes no further. This is what I hoped to resolve with the "Anyone" option, and I think refining further than this is best left out unless we see many users asking for it.

**Comment by hartenthaler** [comment]
> How would this look on the diagram? Would the starting person have their family record with their partner showing (but no children), and then the spouse would have a family record with their other spouse and so on? This actually seems to happen if you disable ancestors and descendants rather than setting them to 0 (but not in combined mode). If this is what you meant, then perhaps we can be a bit more deliberate about which options cause this to show.

For me, the simple mode is already as it should be.
![Screenshot (220)](https://user-images.githubusercontent.com/6324175/182569152-51fb9b18-130a-423b-87d2-38f59faba709.png)
In the combined mode persons which are members of more than one family are duplicated. ok. Maybe it would be nice to link them by a dashed line.
![Screenshot (221)](https://user-images.githubusercontent.com/6324175/182569679-0c127d86-4244-4a3e-995b-7f55a6a41707.png)

> There has been a previous discussion in https://github.com/Neriderc/GVExport/issues/85 that the last descendant generation should have the children of the previous generation but not partners of these children because this generation does not have their family records included.

I do not understand "... this generation does not have their family records included". If there are persons (children) in the last descendant generation and if they are married, then there are partners of those children and they have families in this generation where they are husband and wife. If they should be included may depend on the option "partner". If this is not selected, then I would expect that partners (and family of the partners) are not shown. If the option "partner" is selected, then I would expect that they are shown. If the "any" option is set, I would expect that the partners, their ancestors, and their partners are shown.

**Comment by schuco** [comment]
My argument in #85 was from the perspective that spouses are mainly displayed to define the ancestry of children in the next generation. And as there are no children displayed beyond the last descendant generation, spouses are not necessarily to be shown.
But @hartenthaler is right that if spouses are to be displayed or not should be ruled by the spouses-option and max generations.

Regarding discussion about terminology we may run in a conflict between coining logically correct terms and usability/understand-ability  for normal users.
Replacing siblings by some abstract term has the same correct logic as the replacement of cousins by all relatives. But in my opinion most users will have a better imagination of what will be displayed with the term siblings.

**Comment by Neriderc** [comment]
I _think_ what's being agreed here is that if a generation is included, then their family record with their partner should be included. Their children would only be included if the descendant generations limit set allowed for individuals in that generation.

So from my understanding, the summary is:

- Unselecting "Include ancestors" or setting ancestor generations to 0 would result in the same outcome.

- The family with the starting individual(s) parents is only included if "Max levels" for ancestors is set to 1 or higher.

Effectively I believe there would be no change to how "Include ancestors" and "Max levels" for ancestors are treated at the moment. For descendants:

- Unselecting "Descendants" would not include the family record with spouse of the starting individual(s).

- Selecting "Descendants" and setting "Max levels" to 0 would include the family record of the starting individual with their  spouse but their children would not be linked to the family record.

- If "Max levels" of decendants is larger than 0, the last (youngest) generation shown would have the family record with their spouse shown, but not the children.

Of course spouses are only shown if this is selected in the options.

Have I got this right based on the discussion?

**Comment by hartenthaler** [comment]
Oh, yes - I have forgotten to comment on this; maybe because it is not easy.

For ancestors: 100% agreed.

For descendants: 

> Of course spouses are only shown if this is selected in the options.

ok.

> Would we still show the family record if no kids/spouse are being shown (youngest generation, spouses not selected)?

If there are no kids and no spouses shown it makes no sense to show a family record. This is valid for the simple mode. In the combined mode there is at the moment some logic in avoiding boxes with only one partner. I never fully understood the logic behind that.

> If "Max levels" of descendants is larger than 0, the last (youngest) generation shown would have the family record with their spouse shown, but not the children.

Yes. The children beyond the max generation level are not shown. The partners and the families with the partners only if the partner itself are shown (following the selected options).

> Selecting "Descendants" and setting "Max levels" to 0 would include the family record of the starting individual with their spouse but their children would not be linked to the family record.

Yes. Following the selected options the partners and maybe the partners of the partners are shown including all the corresponding family records.

> Unselecting "Descendants" would not include the family record with spouse of the starting individual(s).

No. For me, spouses are no descendants. They are in the same generation (like siblings). For me, unselecting descendants is the same as selecting descendants and setting the max generation to 0. When unselecting descendants no children should be shown. If partners or partners of partners are shown depends only on the setting of the options "partners" and "any", but not on the selection or not-selection of ancestors or descendants.

**Comment by Neriderc** [comment]
Closing this discussion thread as I have created #201 to make the changes.
