### ISSUE TITLE
Problems when using Edge browser

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#139]
The following problems appeared in my productive system when using the Edge browser:
- closing "x" button  of the menu does not work any longer
- when downloading PNG or JPG there a no images included
- when downloading SVG there are only some images visible

This is working in Firefox.

**Comment by Neriderc** [comment]
The X button no longer working strongly implies this is a javascript error. Possibly Edge needs to be treated in a special way. When I get an opportunity I'll have a look in Edge and see what the issue is.

**Comment by Neriderc** [comment]
I have tested Edge and it works fine for me. Are you using an up to date version? In particular I'm wondering if you're using the Edge that uses the Chrome backend or the legacy version (which is no longer supported by Microsoft). 

Could you make sure you reset the settings (reset button) and hard-refresh the page (shift+refresh), and see if you still see the issue?

If that doesn't help could you check the browser console and see what javascript error you are getting?

Could you see if it works fine when images are disabled? What if you try with a different group of people (perhaps one of the images is triggering an error)?

**Comment by hartenthaler** [comment]
I'm using the latest version of Microsoft Edge: Version 104.0.1293.63 (Offizielles Build) (64-Bit)

The problem regarding the "x" button was solved by clicking the "reset button". The problem regarding the images is still there.
If have tested a person again with Firefox and Edge: https://ahnen.hartenthaler.eu/module/_GVExport_/Chart/ahnen?xref=I99

In Firefox all download file formats are ok. In the browser window using Edge everything is ok. When downloading SVG the image is there. But when using Edge and downloading PNG or JPG the image is missing. This is the case for several tested persons/images.

There is only one error shown in the Edge console: 
```
Asset?asset=js%2Fscript.js&hash=1654449353:1 
Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
    at Asset?asset=js%2Fscript.js&hash=1654449353:1:116
```

**Comment by Neriderc** [comment]
I've had a look at your link and see the issue. The error is not in GVExport, it's in a script from a module "argon". I see an error from this module even before doing anything, and even on pages other than GVExport. I also get errors in Firefox.

Perhaps try disabling this module and see if that resolves the issue?

**Comment by hartenthaler** [comment]
Now all custom themes are disabled. The error message in the Edge console disappeared now.

In Edge there are still no images shown when downloading PNG or JPG. SVG is ok. Can you check it again using the above link, please?

**Comment by hartenthaler** [comment]
![gvexport (1)](https://user-images.githubusercontent.com/6324175/186287687-1faf9e2d-c254-47bb-bca9-1171f4f6d7ec.png)

**Comment by Neriderc** [comment]
Yes, thanks I see the issue and see there are no errors in the console. I have also reproduced this on my own site.

For some reason, the image URLs are not having the image embedded in them. This means when viewing the SVG in your browser where you are logged in to webtrees, the images will show because they are being pulled through from webtrees. If you tried to view this same file in a browser where you were not logged in or in a standalone SVG reading application like Inkscape, the images wouldn't show.

So although it appears SVG is ok, in fact it is not ok.

I think first step is to work out why the SVG is not having its image URLs fixed. I suspect solving that will solve the issue for PNG/JPG. I'll start looking into this.

**Comment by hartenthaler** [comment]
Yes! I observed that the images in SVG are loaded sometimes a bit later after opening the SVG. This is explained by your analysis.

So it is a problem that is specific to Edge and Chrome, but not to Firefox. It does not depend on specific images or specific web server configurations. It is specific to SVG, PNG and JPG. It is irrelevant if the webtrees user is logged in or not and which webtrees theme is used.

**Comment by Neriderc** [comment]
This is interesting because I tested both Firefox and Chrome and it worked fine. In fact, most of the time I was developing this it worked better in Chrome than in Firefox! By the end they were both working equally well. I'm not sure what I've done to break it but I'm happy you pointed out the issue in Chrome as Edge runs the same rendering engine as Chrome so I was confused as to how one could work but not the other. 

I will look into this and see if I can work out what is wrong.

**Comment by Neriderc** [comment]
I worked it out! For some reason, when the SVG is generated in Chrome/Edge (by the Viz.js library emulating GraphViz), the tag attributes come out in a different order than in Firefox. Perhaps some small nuance influences this and that might explain why it was working the other day but no longer is.

I have confirmed that this fixes the PNG/JPG output as well.

I'll need to build this part more robustly so it can handle the differences.
