### ISSUE TITLE
Error in test tree

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#142]
```
Call to a member function spouseFamilies() on null …/modules_v4/GVExport/functions_dot.php:1120
#0 …/modules_v4/GVExport/functions_dot.php(326): vendor\WebtreesModules\gvexport\Dot->addIndiToList()
#1 …/modules_v4/GVExport/functions_dot.php(340): vendor\WebtreesModules\gvexport\Dot->createIndiList()
#2 …/modules_v4/GVExport/functions_dot.php(194): vendor\WebtreesModules\gvexport\Dot->createDOTDump()
```
This happens when using Katharina Löffler (I123) as starting person and opening the GVExport module using the following test file (remove extension .txt !).
[wtcce_IF_(I122).ged.txt](https://github.com/Neriderc/GVExport/files/9392715/wtcce_IF_.I122.ged.txt)

**Comment by Neriderc** [comment]
What other settings? It seems to work fine for me.

![image](https://user-images.githubusercontent.com/89974636/185884848-bf40bd69-f2c0-4a84-bf27-5426a5b41f29.png)

**Comment by hartenthaler** [comment]
Ahh! The reason was a person in the XREF list of starting persons that does not exist. Try to enter an illegal XREF in this list and the error should be visible.

**Comment by Neriderc** [comment]
Great! I have made a small change to skip adding any individual where the XREF is invalid (or more correctly, when webtrees returns a null instead of the individual). This will only work for starting individuals, though in future we could expand this to stopping individuals.

Currently there is no message to let you know that the XREF was ignored. I think it's important to let the user know this, but we don't yet have functionality to pass error messages to the toast system. The toast system only does one message at a time currently which meant it wasn't simple to add in the message. Instead, I have created #146 to upgrade the toast system, and as part of this we'll add the warning message from this as an example to test.
