### ISSUE TITLE
Translation question: unseen links

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#173]
A new string is added: 
`Ignore unseen links to speed up relative check`

But what are "unseen links" and what is the connection with the relative check?

**Comment by Neriderc** [comment]
When displaying part of a tree, it is possible that individuals may be related but the relationship is not part of the displayed area. For example, imagine the case where a man marries his cousin. If you just display the man, his spouse, and their children (with the man as the starting individual), then the spouse will show as non-related because we have only added them as a spouse, and the link via common grand parents is not part of what is displayed.

We therefore add an additional check where we scan all relatives of starting individuals ignoring any generation maximum settings or other settings that limit what is shown, scanning the full tree of relatives to try to find any links that are not displayed on the visible tree but are part of the wider family tree in order to ensure that when we say an individual is not related, we use all our knowledge of the tree and not just the visible part. See #109 for more information.

The problem with this is that it can be slow. So we have added an option to not perform the full scan, and instead only trust what is visible. That is what this option is. See #166 for more information.
