### ISSUE TITLE
Added individuals in last descendants generation not processed

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#184]
Starting to display grandfather **I743** until his grandchildren, i.e. include max. 2 (decendants) generations:
![GVE2110c-1](https://user-images.githubusercontent.com/5896925/188600907-7949a51b-d8ac-4524-8e0f-c81e3d6d2b6b.png)
Adding just one of the granddaughters **I869** does not display her progeny as expected:
![GVE2110c-2](https://user-images.githubusercontent.com/5896925/188601749-26a04bf6-4728-4184-99f0-257a27c79a32.png)
_There are descendants of I869, which could and should be displayed,_ as can be seen setting max. 3 descendants generations:
![GVE2110c-3](https://user-images.githubusercontent.com/5896925/188602355-5683e943-7840-4d14-8205-0fb1a13d582c.png)
If the diagram is set up the other way round, selecting granddaughter I869 first and then adding grandfather I743, this results in the expected tree (max. 2 generations set):
![GVE2110c-4](https://user-images.githubusercontent.com/5896925/188603137-fefe1840-8f60-4c97-82cf-203e17f72e2c.png)

_I checked previous GVE versions and found it worked correctly at least in GVE-2.1.5.1:_
Grandfather alone:
![GVE2151-1](https://user-images.githubusercontent.com/5896925/188603522-68b58a0a-9db7-4cce-bbca-3f58df75b2ce.png)
and granddaughter added:
![GVE2151-2](https://user-images.githubusercontent.com/5896925/188603617-1c9626fc-3d1a-42fd-955d-07685015adbe.png)

It seems, an error has been included after version 2.1.5.1

**Comment by Neriderc** [comment]
This does seem odd as based on how it's done I would expect the same outcome regardless of the order of the starting individuals.

I will investigate this.

**Comment by Neriderc** [comment]
I thought I had this solved but realised there is a further problem that may require a bit of redesign to that part.

I have merged in a fix that will resolve your specific problem, but there will remain an issue if your second individual is not the final generation but is in the middle. I'll have to have more of a think about how to resolve this.

**Comment by hartenthaler** [comment]
What is the meaning of "max generation level" regarding to the starting persons? What is the meaning of starting persons if there are more than one?

(1) The starting persons are independent to each other. The "max generation levels" are used for all starting persons. The resulting set of persons and families is the union set found for all starting persons.
(2) There is a main starting person (in the first line) and other starting persons (XREFs in the second line). The max generation level is more important for the main starting person. There is for each starting person a set of resulting persons and families. The resulting set is a intersection of those sets, limited to the max generation levels of the main starting person.

I thought that (1) is the one that is designed. So there is no main starting person and the sequence of starting persons should be irrelevant. For each starting person a set of persons and families should be build (using all the selected options). Finally the resulting set is the union set of those sets. 

> ... but there will remain an issue if your second individual is not the final generation but is in the middle.

This makes no sense to me, because the second individual is (as it is valid for all starting persons) always in the center (generation 0) of its own set of generations. This individual is only in its final generation if there are no ancestors and descendants selected or both max. generation levels are set to 0.

As an example: there are two starting persons: A and its greatgrandfather G. The options "ancestors and descendants are selected and both max generation levels ar set to 1. So I would expect that the resulting diagram shows A and the parents and children of A. And it should show G and parents and children of G. The children of G are the grandparents of A. I would expect that GVExport is showing all those persons and families.

Now something new: Some of the children of G (the grandarents of A) are related to the parents of A, so you could expect that those family relations are additionally shown in the diagram. So to be precise: the above mentioned union set of resulting persons and families of the starting persosns is the union set of the persons and families can be enriched by the connecting families between those sets if a member of one set is related in one step to a member of another set. But maybe this is too sophisticated.

**Comment by Neriderc** [comment]
> I thought that (1) is the one that is designed. So there is no main starting person and the sequence of starting persons should be irrelevant. For each starting person a set of persons and families should be build (using all the selected options). Finally the resulting set is the union set of those sets.

Yes this is my understanding too. However, this is not how it works behind the scenes. One single list of individuals (and one of families) is assembled based on settings. Herein lies the problem.

> > ... but there will remain an issue if your second individual is not the final generation but is in the middle.
> This makes no sense to me, because the second individual is (as it is valid for all starting persons) always in the center (generation 0) of its own set of generations. This individual is only in its final generation if there are no ancestors and descendants selected or both max. generation levels are set to 0.

The technical issue here is that one list is assembled. In implementing the "anyone" option, I had to be more aggressive in culling duplicates. It would get stuck in loops adding the same people over and over. Therefore, in most circumstances, an individual already in the list is not added again (and their links to others are not checked again).

However, this de-duplication means that if the second starting individual is added to the list by the first one, then it is skipped and never gets started.

I initially thought that I could get around this by effectively providing an exemption to the starting individuals, but after thinking about it a bit more I realised that the starting individual could appear anywhere in the diagram, and in this case the descendants are still skipped as they already exist in the list and aren't one of the starting individuals.

The logical thing in my mind is to build the trees for each individual separately, and then combine them before drawing the diagram.

> Now something new: Some of the children of G (the grandparents of A) are related to the parents of A, so you could expect that those family relations are additionally shown in the diagram. So to be precise: the above mentioned union set of resulting persons and families of the starting persons is the union set of the persons and families and can be enriched by the connecting families between those sets if a member of one set is related in one step to a member of another set. But maybe this is too sophisticated.

I agree this would be nice. These links outside the criteria are not part of the information currently collected. We in theory could also store all links for a record even if the records they link to aren't in our diagram, then strip out any links that go nowhere... but as you've suggested we are getting a bit sophisticated. If you're really keen to have it I'd be happy to have it on the back log to look at some time in the future.

**Comment by Neriderc** [comment]
Right, I think I've solved this one (by doing what I described above - changing the code to generate independent lists of individuals then merging them).

@hartenthaler you may want to test to see if it now follows your expectation

@schuco if you wanted to test this ahead of the next release, you could go to the[ main page](https://github.com/Neriderc/GVExport) and look for a bright green button near the top that says "Code". Click this and then click the "Download ZIP" button. You can unzip this and install to the modules_v4 folder.

**Comment by schuco** [comment]
@Neriderc thank you. It works fine, also for the second selected individual in the middle of max generations

**Comment by hartenthaler** [comment]
> If you're really keen to have it I'd be happy to have it on the back log to look at some time in the future.

No. Keep it simple. It is still complex enough.

> @hartenthaler you may want to test to see if it now follows your expectation

It is better than ever before. You are doing a great job!!! It does not follow my expectation regarding showing partners or not. But this is related to #101. Sometimes in the simple mode partners are not shown even if "partner" is selected.
