### ISSUE TITLE
Error after timeout

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#186]
This morning I pressed the "Update" button and got the following error message. During the night there was a timeout of my webtrees session. After logging in again everything was ok again.
![Screenshot (241)](https://user-images.githubusercontent.com/6324175/188613676-97c32c4e-b105-481c-9d56-e61fca16cf21.png)

**Comment by Neriderc** [comment]
I have seen this a lot. webtrees logs me out often during development (I'm not sure why).

The error happens when your page thinks it's logged in but the backend does not. Refreshing to bring up the logged-out state of the page fixes this. I've never actually investigated this any further.

I've had a bit of a play now and it's due to how the browser render is built. The javascript submits a request to the server to download the DOT file, and expects this DOT to be what is returned. However, in this case what is returned is actually a full HTML webtrees page with a message saying the form has expired, please try again.

It should be easy enough to detect if a DOT or an HTML page is returned. I'd propose if we end up with this error we should just refresh the page?

The settings that would have just been submitted won't be saved because webtrees is rejecting the login, but the user is going to have to refresh to continue anyway so we might as well do it for them. 

An alternate would be to show a toast that says they have been logged out and need to refresh.

Or both, I guess. We could show a toast that says they are no longer logged in and we need to refresh - then after 1 or 2 seconds trigger a page refresh.

What do you think?

**Comment by hartenthaler** [comment]
> I'll tag this as enhancement as the error is genuine, we just want to handle it in a nicer way.

Yes, this would be nice.

Your idea with a toast message is good. And then triggering a page refresh should be helpful.

**Comment by Neriderc** [comment]
Great, from my quick look I think this shouldn't be too hard to do.
