### ISSUE TITLE
Color of arrow to adoptive child is not correct (persons from clippings cart)

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#197]
![Screenshot (247)](https://user-images.githubusercontent.com/6324175/189664089-1999ed29-f7fa-45c7-b33c-47a395648d20.png)

The color of the marked arrow is wrong. The persons and families are from the clippings cart.

**Comment by Neriderc** [comment]
I have just merged in a pull request that solves this, so you should be able to use the main branch to have this working.

I also noticed while reproducing this that when using the clippings cart with combined mode, _no links at all_ are shown. Combined mode with clippings cart records was completely broken. I managed to trace this back to the commit when I implemented these coloured arrows.

In order to solve both of these issues, I have made a fundamental change to when the relationship check happens. I had been trying to avoid checking twice (once checking for adoptive/etc links when colouring boxes, once for arrows) but this hasn't worked as I've intended so now we run the check twice. However, it seems to work great now and that's the main thing :)
