### ISSUE TITLE
Using temporary files

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#28]
I have not looked in detail at the usage of temporary files in GVExport. Can/should this functionality be replaced by IndexedDB like it is used in the custom modules [TAM](https://github.com/huhwt/huhwt-wttam) and [Lineage](https://github.com/huhwt/huhwt-wtlin)? See [architecture diagram](https://wiki.genealogy.net/Webtrees_Handbuch/Anleitung_f%C3%BCr_Webmaster/Erweiterungsmodule/TAM_und_Lineage).

**Comment by Neriderc** [comment]
I've pondered over this for a while but I don't know that we can do away with the temporary file because this is fed into GraphViz installed on the server. I think the DOT file is the only temporary file generated? And it just gets overwritten each time.

In theory, this shouldn't be needed if you don't have GraphViz installed, but removing this would involve substantial work to change how things are done.

I'm not sure I understand the benefit of doing this?

**Comment by hartenthaler** [comment]
So let us close this issue.

In the case of TAM and LIN, both sides (sending and receiving) are new developed applications, so it was possible to use IndexedDB for the data exchange instead of writing a temporary file. But if Graphviz (installed on the server) needs a file it is impossible to change that.
