### ISSUE TITLE
Scroll browser diagram to the person last added

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#285]
After you have added a person to the starting list the browser diagram is centered around the first added person. Especially in a big diagram it would be more helpful to srcoll to the person last added.

**Comment by Neriderc** [comment]
Done!

It now scrolls to the last person on the XREF list. In practice, this will mean that when you add someone new the diagram will scroll to them when loaded.

A small side note, when you first load the page, if you have a list of people, the order they appear in the list is not well defined. What happens is that the page will send a bunch of requests to webtrees for the details, and then when it gets a response for each one they will be added to the list. It's possible that the requests come back in a different order than they were sent (if one takes longer to load), so the list won't necessarily be the same order each time you load the page. I mention this only because when first loading the page the scroll may not go to the person you expect (it always does the last person in the XREF list, in the box in the advanced settings). In my view this is not an issue as when first loading the page we can only scroll to one person, and any person is as good as another. With the context of adding an additional person we now have a reason to prefer this person to scroll to, and that should work fine.
