### ISSUE TITLE
New sex "X"

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#29]
webtrees now supports the sex "X" beside M, F, and U. X is used in GEDCOM 7.0 to indicate a gender beside M and F. This should be considered in GVExport.

**Comment by Neriderc** [comment]
Sorry this is long by I think it's important to get right.

Currently GVExport shows Female as Pink, Male as Blue, and anything else as Grey. I've tested, and this includes "Other" (X). GVExport doesn't choke on it, it just treats anything as not M or F as unknown.

As I understand it, the only place GVExport uses this information is in colouring the boxes. So I guess the question is whether we should have another colour for X (which on the surface seems logical), and if so, what that colour should be.

I've had a look at the [GEDCOM standard [PDF]](https://gedcom.io/specifications/gedcom7-rc.pdf) and it has this to say:
![image](https://user-images.githubusercontent.com/89974636/174198597-64802754-29bd-4453-85c5-f184a9666ddf.png)

It makes it clear it's not about gender identity (e.g. not agender, non-binary, etc) but is specifically about anatomy at birth (male, female, intersex). With a bit of a search I came across[ this article](https://intersexday.org/en/symbols/) which mentions in the section "The Intersex Flag":

> The colour yellow has long been regarded as the hermaphrodite colour … Purple, too, has been used for the same purpose … The circle is unbroken and unornamented, symbolising wholeness and completeness, and our potentialities. We are still fighting for bodily autonomy and genital integrity, and this symbolises the right to be who and how we want to be. 

I was worried that X might encompass more than just Intersex but t[he wikipedia](https://en.wikipedia.org/wiki/Intersex) page describes Intersex as:

> Intersex people are individuals born with any of several sex characteristics including chromosome patterns, gonads, or genitals that, according to the Office of the United Nations High Commissioner for Human Rights, "do not fit typical binary notions of male or female bodies".

So it seems _by definition_ "Other" in webtrees means "Intersex".

So with that said, perhaps yellow would be a good colour? A similar shade to the linked flag, but reduced saturation to match the other colours.The only problem with this is that the "family" colour that shows the marriage date is also yellow. It would be pretty much the same colour, but in a different place. 

Is that ok? It might be ok to use the same colour since they are in different places. But it might not look right. I would be worried about using the other mentioned colour (purple), because it is also associated with sexual orientation, which is a concept not related to intersex.

**Comment by Neriderc** [comment]
On this, I noticed webtrees itself uses a shade of yellow as well (I can't believe I forgot to check this first). I also noticed it uses a shade of green for unknown, do we want to match this?

**Comment by hartenthaler** [comment]
To use colors similar as they are used already in webtrees is a good idea.

**Comment by Neriderc** [comment]
I've updated default colours and added support for gender X. The shade of yellow is quite different to the family yellow so I don't think there's any issue there. I've also changed "Unknown" to the shade of green webtrees uses, instead of grey.
