### ISSUE TITLE
Switching to other tree

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#293]
If you have several persons in the start person list and switch to another tree you will get a pop-up message that those persons are not available in the new tree, which is not surprising. I would assume that if an XREF of a person is in the start list from the first tree is also available in the second tree that this person will be shown which is not intended.

I suggest storing the tree ID together with all the XREFs in the start and stop list in order to clear or restore those lists whenever you change the tree.

**Comment by Neriderc** [comment]
Good idea! This should be pretty straightforward. Currently a cookie is saved with the saved settings. We should save a different cookie per tree.

**Comment by Neriderc** [comment]
Done. This keeps completely separate settings per-tree. This is for a few reasons. Firstly, it's much easier to do :slightly_smiling_face: . And secondly, I think this is a better way to do it rather than only saving the XREF selection per tree.

Different trees have different individuals and different families. You are likely to want to select a different number of generations, different stopping persons, etc. If you want to set some settings across all trees, you can use the control panel settings. 

If there's demand for it, we could consider either including some fields across trees and some specific to trees. This would mean changing how the data is saved, but to be fair I'd like to do this anyway at some point.

Alternatively, we could implement an advanced setting to load the settings from another tree.
