### ISSUE TITLE
Do not show dates and places is not possible anymore

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#310]
When testing the latest development version I observed, that it is not possible anymore to switch off the display of birth/death/marriage dates and places.

**Comment by schuco** [comment]
I do not even get a diagram. Also "x" to switch off the menu does not work.
I have made a reset before

**Comment by schuco** [comment]
I forgot to report, that some days ago I did not get a diagram too. There appears no totating tornado symbol as after normal refresh before you get the diagram.

**Comment by Neriderc** [comment]
> When testing the latest development version I observed, that it is not possible anymore to switch off the display of birth/death/marriage dates and places.

Thanks for reporting!



> Using the latest master I do not even get a diagram. Also "x" to switch off the menu does not work. I have made a reset before

If the X doesn't work, this is a sign of an error that stops the rest of the code running. Could you right click on the page, choose "Inspect", click the " console" tab in the panel that opens, and see if there is anything listed in red?

**Comment by Neriderc** [comment]
And another issue I've found, I'm not convinced it's properly using Graphviz on the server if installed. I'll need to look further into this.

**Comment by Neriderc** [comment]
Click the Console tab, I'm guessing it's where it says "Konsole" :slightly_smiling_face:

**Comment by schuco** [comment]
![grafik](https://user-images.githubusercontent.com/5896925/208885624-cdd0df19-0c20-4e28-89ae-b76ce74b0fea.png)

**Comment by Neriderc** [comment]
Many thanks! If you click on the top line where it says index.php:1611:4 could you show me what it shows you?

When did you last update? do you still get this if you delete the module and download it clean? (Unless you've done this in the last 24 hours in which case nothing would have changed).

Do you still have the issue if you switch to English?

**Comment by schuco** [comment]
Sorry I can't respond immediately, I am away just with the mobile phone

**Comment by schuco** [comment]
` If you click on the top line where it says index.php:1611:4 could you show me what it shows you?`
![grafik](https://user-images.githubusercontent.com/5896925/208954138-75e29d6b-ca31-456a-b8b8-028c2b1c33ea.png)

`Do you still have the issue if you switch to English?`
Yes, same error (no diagram)

**Comment by schuco** [comment]
`When did you last update? do you still get this if you delete the module and download it clean? (Unless you've done this in the last 24 hours in which case nothing would have changed)`.
I deleted the module on the server and reloaded main just now. Same error.
I hope it is no problem when I leave older versions on the server's modules_v4-folder after deactivating by a dot like GVExport-2.1.16

**Comment by Neriderc** [comment]
> I hope it is no problem when I leave older versions on the server's modules_v4-folder after deactivating by a dot like GVExport-2.1.16

No, this should be fine.

Thanks for the screen shot. I think the error didn't load properly, often this happens if the page hasn't been refreshed in a while when you click on it. Could you try again, in this order?

- Right click -> inspect page, go to Konsole tab.
- Refresh the page
- Click on the "index.php" part of the first error listed in red

I'm hoping it will show you some code so we can see exactly where the error is being generated.

Does it help to use different starting persons? I'm wondering if there might be something special about some of the data being fed in. It's pretty concerning that you get such a serious error and I can't replicate it! I would very much like to get to the bottom of this.

**Comment by schuco** [comment]
![grafik](https://user-images.githubusercontent.com/5896925/209100088-9d670149-d012-45d8-ac51-17abeda1ba98.png)

I am not sure what you mean with "Refresh the page". Is it Reset by the menue or entering another starting person?
What you see is the result of Reset by the menu

**Comment by Neriderc** [comment]
I meant refresh using the browser's refresh button, which I think you did. Thanks for that. The way it's gone to here instead of highlighting a piece of code is not quite what I expected. I'm starting to suspect the error is coming from one of the add-ons we are using (caused by something we are telling it that is wrong), and perhaps this will not be helpful - but could you try one last thing. In the earlier screen shot it has 1611:4, this is referring to line 1611 and position 4 (counting from left to right). Could you scroll that little code window in the latest screen shot, down so that you reach line 1611? The numbers on the left counting 1, 2, 3, 3 down the side are the line numbers, so just jump to where you see 1611.

Are you logged in or out when you get the error?

It's getting late here so tomorrow I will try to set up a development environment running PHP7.4. I don't expect this to be the issue, but at this point I think it's worth trying since we aren't making progress :slightly_smiling_face:.

I've also found an issue with cookies for logged out users, so I'll need to investigate this as well.

**Comment by schuco** [comment]
` Could you scroll that little code window in the latest screen shot, down so that you reach line 1611? The numbers on the left counting 1, 2, 3, 3 down the side are the line numbers, so just jump to where you see 1611.`
![grafik](https://user-images.githubusercontent.com/5896925/209109742-af5c7d6d-2343-4f9d-88e8-ad30fe8f9f1b.png)

I hope I did what you expected

`Are you logged in or out when you get the error?`
I am always logged in. Access to diagrams etc. is only given to members, not to just visitors

**Comment by Neriderc** [comment]
> I hope I did what you expected

Perfect! I think I see the issue! I do not really understand why it causes an error for you and not me, but I will fix it when I am able to.

> As you go to bed we prepare for a pre-christmas event with our children and grand-daughter this evening. Next days we will be away for the "real" christmas event with an even bigger family group ion the former family farm. As I may not be able to follow this issue the next days I already now wish you to have relaxing and peacful christmas days and a happy new year. 

And the same to you! Enjoy your Christmas 🙂 

> Thank you again for the great work you have done to make GVE the most attractive part of webtrees!

It's my pleasure. It started with just needing it to keep working as I was using it extensively and after one webtrees update it stopped working for me (which turned out to be when the container I was using upgraded to PHP8). I may have stopped there but all the feedback, suggestions, and reporting of issues from yourself and @hartenthaler has given me the enthusiasm to take things a lot further! 

On top of the issues reported here, I keep finding issues with this release so will not release 2.1.17 until sometime after Christmas. I'd suggest rolling back to 2.1.16 in the meantime.

In the background I've been working on automated testing, but as you can imagine there are a lot of settings and so a lot of things to test. Hopefully one day it will be very easy to know what is or isn't working after a change!

**Comment by hartenthaler** [comment]
Marry Christmas!

**Comment by Neriderc** [comment]
I've put in some updates into the main branch. @schuco can you give it a try and see if your issue is resolved?

All other problems mentioned in this issue should also be resolved.

**Comment by schuco** [comment]
` @schuco can you give it a try and see if your issue is resolved?`
The diagram works now. Also "X" removes the menu.
But "load settings from file" results in in some internal action (rotating symbol) however the previous setting remains as if nothing had been loaded.
The stored json-file had before been downloaded with the most recent GVE-version

**Comment by Neriderc** [comment]
Because of the huge changes in how things are saved, any file that wasn't downloaded with this latest version won't work properly.

Any setting unrecognised should be skipped, so the result is probably that the diagram is loaded again with very few changes (possibly some settings are loaded but match what the settings are already set to).

To support saving multiple versions of settings in #299, there will be more changes (because I hit a limit of the setting name length, which is a lot shorter than the setting value maximum length - so settings will need to be renamed). Therefore I suggest not spending too much time on creating saved settings until 2.1.17 is finalised. _Probably_ the XREF list setting name will not change so that is probably safe.

If you're having trouble with loading settings that were downloaded with the current version, that would be good to know. I have an automated test for this so as far as I know it works, but problems can definitely sneak through!

**Comment by schuco** [comment]
`If you're having trouble with loading settings that were downloaded with the current version, that would be good to know.
`
Unfortunately this happens in my case. Just now I downloaded a setting with two starting persons, did a reset resulting in a chart with the default starting person and then reloaded the file downloaded just before. As already described  there was some activity (rotating symbol) but old settings remained.

**Comment by Neriderc** [comment]
Hmm ok thanks. I'll take a look and see if I get the same thing.

**Comment by Neriderc** [comment]
Ok I think I've resolved this in #313 

Basically the issue was not with loading, but with saving. This is why the test did not pick it up, I didn't yet have a test for saving as I hadn't worked out how to do this. I now have a test for saving the settings file, but this assumes I got it right so please give it a test and tell me if you find any issues!

**Comment by schuco** [comment]
I ran in 
trouble updating webtress. It will take some days to have it running again. So sorry, no test possible at the Moment.

**Comment by Neriderc** [comment]
Not a problem, give it a test when you can. I'm a little behind on webtrees updates, I hope I don't have to be worried about updating!

**Comment by schuco** [comment]
`I hope I don't have to be worried about updating`!
From webtrees homepage: 
webtrees 2.1.8 and 2.1.9
These two versions of webtrees contain a bug in the auto-upgrade code. The upgrade will appear to run successfully, but it does not install any files. The bug is in the file app/Http/RequestHandlers/UpgradeWizardStep.php. You can download an updated version of this file from [here](https://raw.githubusercontent.com/fisharebest/webtrees/3bcf98433336b5a90f37394d98c25184064324ae/app/Http/RequestHandlers/UpgradeWizardStep.php).

**Comment by Neriderc** [comment]
Thanks for that! I feel a little bad that I'm still running 2.1.7 when the latest version is 2.1.15. It lools like I won't be affected by this, but I may not have been affected anyway as I am using Docker and I don't think this would have been a problem based on the description.

I really need to get on to updating to make sure GVE runs well with the latest version.

**Comment by schuco** [comment]
First of all I wish all of you GVE-fans a happy New Year!

I went back to webtrees 2.1.8, and tried the actual GVE-main.
Unfortunately it still does not work to reload a setting file. I only get the previous starting person.
Here is what I see in the console:
![grafik](https://user-images.githubusercontent.com/5896925/210263131-52b38cfd-3ddc-47a9-91e7-94ca6cb38804.png)

**Comment by Neriderc** [comment]
Happy New Year to you too!

This is an interesting error. Are you able to show the right side to and to click on it to show where the error comes in the code like you did the previous time?

I actually wonder if this is a red herring - from my research it seems this is a common error caused by extensions, but it's perfectly possible it is not affecting the page.

I have found an issue with loading XREFs and have fixed this in the latest pull request, so if you could try installing from the main branch again we can see if that fixes things.

I also found my automated test does not include the XREF loading :facepalm:. I wrote the tests for the control panel page first, then copied them for the user settings. The admin page doesn't have an XREF setting so it was missed (same with stop XREFs). I'll need to add that to my tests but in the meantime I think (hope) I have solved the issue.

**Comment by schuco** [comment]
` Are you able to show the right side to and to click on it to show where the error comes in the code like you did the previous time?`
![grafik](https://user-images.githubusercontent.com/5896925/210418972-3cf550b4-abe7-4d74-ae4d-700887a0b850.png)
after clicking 
![grafik](https://user-images.githubusercontent.com/5896925/210419624-a1b954a1-eb59-4db6-9a47-f74d2bc69260.png)

![grafik](https://user-images.githubusercontent.com/5896925/210419391-a8ed9ea0-5930-4320-862f-c2137f34f4e1.png)

**Comment by schuco** [comment]
I tried the main from today.
Now it generally works.
After loading the file with settings for a chart with 2 starting persons thes persons are displayed in the menu, but the chart is only for the previous starting person, i.e. it was not refreshed.
After e.g. changin number of generations it comes up correctly and completetly for the  2 starting persons

**Comment by Neriderc** [comment]
I've just pushed a small change to fix this.

I think everything in this issue is now resolved?

**Comment by Neriderc** [comment]
Also, thanks for those screen shots. It seems my instinct was right, it looks like the AdGuard extension has the error. I think this can be ignored, so long as the page is running ok now.

**Comment by Neriderc** [comment]
I found an issue with saving the settings to webtrees preferences. As far as I know there was no user impact, but the JSON downloaded file was not quite what I wanted and so I've made changes in  #317.

In theory everything should still work fine. I've added XREF loading to my automated testing but it's not foolproof. One big gap is that the automated testing currently only tests that settings are saved and loaded ok, there is no testing for whether the diagram is correct based on the settings (that's a big job that I haven't got to yet). Therefore it would be great if you could update to the latest version on the main branch and report any issues you come across. I'll leave this issue open a bit longer so you can report any issues here.

Assuming it all works ok, I'll go back to working on saving multiple versions of settings within GVE. I really want this to be part of 2.1.17 as we have made big changes already that mean all the saved settings will be lost when people upgrade. I want to make sure we don't need further changes for saving multiple versions of settings causing another loss of settings, so I want it to all be in 2.1.17 so we only have this issue once (hopefully).

**Comment by schuco** [comment]
I used the most recent main. Reloading saved settings works fine.
What I observed now, but what may have been already in previous versions, is that after reloading the options menu gets unfolded displaying special options when  it was not showing special options before and also not, when the settings were saved.

**Comment by Neriderc** [comment]
I'll close this now as I haven't heard about any more bugs. As always, create an issue if you find one!
