### ISSUE TITLE
What happens if stored options for a tree exist and the tree was deleted?

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#318]
I assume that you store the saved options together with the tree ID (the XREFs are always related to a tree).

When starting GVExport with tree "n", then only stored sets of options for this tree should be offered to be loaded. So a set of options for tree "x" is not offered. Correct?

Maybe in the meantime, the tree with ID "m" was deleted. It makes sense to delete the settings for such unused trees from time to time. Otherwise, the database will contain a growing number of settings for trees that do not exist anymore.
I just found some code in the custom module FancyImagebarModule.php. Maybe this is helpful as an example of such a situation.

>        $tree_id = $this->getPreference('last-tree-id', '');
> 
>         try {
>             $tree = $this->tree_service->find((int)$tree_id);
>         } catch (Exception $ex) {
>             // the last tree saved doesn't exist anymore. Use the first tree instead.
>             $tree = $this->tree_service->all()->first();
>             $tree_id = $tree->id();
> 
>             // remove settings from non existing tree from the database
>             DB::table('module_setting')
>                 ->where('module_name', '=', $this->name())
>                 ->where('setting_name', 'LIKE', '' . $this->getPreference('last-tree-id') . '-%' )
>                 ->delete();
> 
>             // reset the last tree id
>             $this->setPreference('last-tree-id', '');
>         }

**Comment by Neriderc** [comment]
I would expect this to be handled by webtrees. We do not directly access the database, rather, we save preferences (specific to user and tree) using $tree->setUserPreference().

Because it is set this way and not directly in the database, webtrees is aware of the tree-specific preferences. They are added the same way as any other webtrees setting, and therefore should be cleaned up in the same manner. I'm not familiar enough with the webtrees codebase but would be pretty confident these would be cleaned up when a tree is deleted.

An exception to this is that if GVExport is accessible when logged out - we then fallback on the old cookie system. In this case, the cookie will stay in the browser until expiry (1 year), or if a tree is created with the same name then it will load those settings.

With regards to the Fancy imagebar module code above, JustCarmen mentioned on the webtrees forum using a tree prefix in the module settings. This would necessitate manually removing items for deleted trees. We are bypassing module settings and saving directly using the webtrees preferences (which Greg said is fine for modules to do), so this is not an issue for us.

One related problem is that because we are using webtrees preferences and not module preferences, if the module is removed we get no opportunity to delete the preferences - these would then stay until the tree or user is deleted as webtrees is not aware that the preferences are module specific. To solve this issue, I'd like to add a button to the admin page to completely clear out all GVE preferences (which would be for all users/trees). The code about may be helpful for this, though I think it would be safer to delete them via webtrees function. The problem with this is that we have to be sure we name all of them, which is probably ok as we can keep items in our list whether still used or not. This is my preferred method as I'd like to stick to using the webtrees-provided functionality where possible instead of directly accessing the database. This provides a level of abstraction that protects against changes in webtrees (The setUserPreference() function saves the settings - we don't care how. Therefore, the way data is saved or the place in the database can be changed and this does not matter. If we directly access the database, then we need to be careful that a change in the database model doesn't mean we are deleting the wrong things. By using the webtrees functions we have protection against this).

So with regards to your concern, I believe this is not a problem as we are letting webtrees handle the detail instead of trying to do this all ourselves.

**Comment by hartenthaler** [comment]
You are right! 

If you delete a module that has been used the function to store preferences, then there is a message when you open "Control panel / All modules" indicating that there are settings but the module is not installed anymore. And there is a button to delete those settings from the database. I have forgotten about this function but just tested it. 

This problem was already solved. Sorry.

**Comment by Neriderc** [comment]
Not quite! So there are multiple places to save settings. There are module specific settings (the kind you save in the Control Panel), these are saved with module->setPreference(). These are kept in a separate module preferences table and these are what can be deleted using the message you describe.

Our user and tree specific settings are not saved in this way. We use $tree->setUserPreference(), and webtrees uses the same function for it's own use (after all, webtrees is mostly a bunch of built-in modules). There is no separation of these settings per module, and so webtrees does not know if it is related to a module or not. There is no warning message for this as it does not know if a module is needed to use the preferences. However, it does know that it's related to a specific user and tree, and when deleting the tree/user webtrees would clean these up the same way it would clean up all tree/user settings that it set itself.

If we set user/tree specific preferences and then the module is removed, webtrees has no way of knowing these settings are no longer needed (as they aren't associated with the module the same way module settings are), and no message for this would be shown. We don't have a way of catching this when the module is removed (once it's gone of course we can't run any code), but I'd like to add a cleanup option to the control panel. This way there is actually a way for an admin to clean up. We could then add uninstall instruction to the wiki or readme.

**Comment by hartenthaler** [comment]
Ah! Thank you! I mixed up those things.
