### ISSUE TITLE
How to update "settings"?

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#323]
I can store settings and give them a name like "Relationship between x and y". I can delete such a setting using the "x". I can use the same name twice, which is unusual but ok.

Is there a possibility to change a "settings"? Load it, make some modifications, type again "Relationship between x and y", save it and delete the old version of this "settings" seems to be possible but complicated.

**Comment by Neriderc** [comment]
Names are just a property in the settings, the settings are saved as an ID, so there's nothing that stops you using the same name twice.

There's not currently a way to update settings without deleting and re-saving them. I'm happy to consider this, how would it work? Are you thinking something like if you put the same name it overwrites the settings? Clicking on settings to load them could also pre-fill the name into the saving box in case you want to save changes without having to type the name again.

**Comment by hartenthaler** [comment]
I think prefill would help me, because I made two typos when playing with long setting names. But would another user understand that the prefilled value can be overwritten? Maybe not. 

Beside the "x" button a save button that overrides the existing setting with the actual values?

**Comment by Neriderc** [comment]
I'm not really sure how we could add another button for overwriting settings where it would be obvious what it's for. The X only works because it's a common UI element that people are used to. Even if you had a little floppy disk icon I still don't think it would be clear what it's for.

If we instead loaded the name into the box, I think it would not confuse users. You would have to first save some settings, then you would see this is the box to type a name in. Then for it to be prefilled, you would then have to click to load settings.

So after you have typed a name, saved some settings, then clicked to load the settings, only then would the name of the loaded settings be pre-loaded into this field.

Personally I think this is clearer to users than adding an extra button.

We would also have a warning message if you try to save settings with an existing name, like "Settings with this name already exist. Overwrite?". This would also indicate to users that they can change the name.

**Comment by Neriderc** [comment]
I have added #327 to address this.
