### ISSUE TITLE
Shared settings URL does not work when Auto update is disabled

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#346]
When I use an URL embedded in a story and auto update is disabled the diagram does nor come up

**Comment by Neriderc** [comment]
Thinking about this a little, the person creating and sharing the settings has control over every part of the settings, including auto-update. If auto-update is disabled, instead of showing the diagram, should we leave the diagram not showing and but leave the settings visible?

This way if you want to share settings and not have it go straight to the diagram, this provides a way to do so. If you want it to show the diagram and hide the settings panel, you can enable auto-update.

At the moment the functionality is not really suiting either case, because the settings are hidden and the diagram is not loaded so you end up with a blank page. But my suggestion is to not load the diagram (because auto-update has been disabled and that's what it's for), but change it so it doesn't hide the settings panel.

Thoughts?
