### ISSUE TITLE
"Don't colour these XREFs" and adding illegal XREF

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#354]
When adding the erroneous  "i123" as XREF instead of the correct "I123" there is no reaction. That should be handled as the XREFs for stop/start persons.

**Comment by Neriderc** [comment]
Hmm this one is a little trickier. In the case of the others, we are loading the details. We submit a search request to webtrees, find the result that matches the XREF case-insensitive, then we update our list to match the case of that search result.

We could do this, but the difference here is that we are already loading the details for the others. This would be a new bunch of requests to be sent and it could make the page load slower.

Since we know that webtrees doesn't allow the same XREF with a different case, and since this setting is not a key one but is a niche and quite hidden setting, could the answer here be to do the XREF check case-insensitive? i.e. make it work, but don't update the list with the correct case?

**Comment by hartenthaler** [comment]
>  i.e. make it work, but don't update the list with the correct case?

This is a pragmatic and good approach. 

Another idea: "Don't colour these XREFs" does not need free text input, because the list of start XREFs is already defined. So another possibility for the GUI would be a dynamic list with check boxes of the defined XREFs.

**Comment by Neriderc** [comment]
Oh that's a much better idea! Let's do that.
