### ISSUE TITLE
 "†" is not possible as death date prefix

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#359]
I tried to use "†" as a symbol for death information (instead of "+"). When I set this character in the control panel it is not stored (no error message):
Administrator settings / Death date prefix.

**Comment by Neriderc** [comment]
As a security precaution, what you can enter is restricted. It was initially restricted based on alphanumeric plus a bunch of symbols from a keyboard, but it would be good to expand this.

I'm doing some research on using unicode categories to allow a much wider range of characters, e.g. 🪦, ⚰️, ⚰, 💀, ☠, etc.

**Comment by hartenthaler** [comment]
At the moment the webtrees database cannot store Emoticons.

**Comment by Neriderc** [comment]
Ah yes I see that now. If people really want to we could still make it work (e.g. detect and convert to a code and convert back when loading). Would mean we would have to choose which ones are allowed. Could allow for something like this: 
![image](https://user-images.githubusercontent.com/89974636/219512647-9238a264-9f0d-44fb-b710-95af599b285d.png)

However, perhaps the better option is to just add the † as an allowable character and if any others come up then add them as they are requested.

**Comment by hartenthaler** [comment]
Your screenshot looks great! The icon style fits the image style. But I would prefer a more serious style. 

I prefer the dagger symbol more than the plus symbol.

**Comment by Neriderc** [comment]
I prefer the more serious style too. Thinking about it, I think the emojis only look OK because the image is a cartoon person. They would look a lot more out of place with a real photo.

I will update the default symbol to the dagger and add it to the allowable list of characters. 

We should also incorporate some validation on the form. It would be better to show a message to the user at the time they are entering an invalid value, rather than have the experience of not knowing something is not valid and then ending up with a blank field.

**Comment by Neriderc** [comment]
I've completed these changes
