### ISSUE TITLE
Make size of shown images adjustable by the user/admin

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#360]
At the moment the image size of the preferred photo of a person cannot be changed. It would be nice to have an option for that.

Simple: In % to the existing value.

More complex: set height and width in pixels; use quadratic, rectangular, circle, or oval shapes for the image.

**Comment by Neriderc** [comment]
The simple option should be simple enough. Currently the size is actually based on the font size, but it would be easy enough to allow adjusting it as a %. Changing this may lead to display issues with how the tile is laid out but probably this isn't an issue and is expected if you change the size by too much.

The complex option is more... complex. Setting the height and width in pixels could be done, but if some photos are landscape and some portrait, or even just a slightly different aspect ratio, this is going to cause issues with stretching (or perhaps we want to cut off the parts that don't fit?).

Using shapes is probably doable, but if the shape didn't line up in the right place on the photo, then what options would we have for correcting that?

I think this stuff if probably doable once we work through the detail of it.

**Comment by hartenthaler** [comment]
JustCarmen has developed some functions for her image bar module. That can be used as an example. 

The new custom theme "modern" uses circular images instead of the rectangular ones. I like them.

**Comment by Neriderc** [comment]
We are a little special. For that module and theme, they can use CSS to modify the image. For example, if you disable the border-radius property in the modern theme, you'll find the images are actually square (i.e. the circle is done in the browser not the server).

Now this is all well and good, but in our diagram we are not actually using HTML and CSS, the diagram is an SVG image. It has it's own rules. Luckily, SVG actually supports CSS styling.

Which is all well and good, except we have an extra hurdle. We are passing our styling through the Graphviz program, which has it's own set of styling rules. This makes it tricky.

Possibly we can pass through the styling, possibly we could add the style to the SVG after Graphviz has generated it. It will take some playing with. But I do like the idea. We'll leave this out of 2.1.17 but I'll find some time to have a play and see what I can get working.

**Comment by Neriderc** [comment]
I've started to have a play at getting circle shaped photos and have not been able to find any way of getting the instruction through Graphviz. I _have_ made some progress in applying styling _after_ the SVG is generated. However, this leads to a problem.

With this method, if you have GraphViz installed on the server, the circle photos will not show in downloaded files. This is because Graphviz directly outputs the PDF/PNG/JPG etc, and unless you specifically choose SVG then there is no opportunity to edit the SVG data like we can in the browser. We end up with a situation where if you install Graphviz, you lose functionality.

One possible answer to this is that we automatically disable Graphviz when this functionality is enabled. We could show a message to the user, but I'm mindful the user may not know what it means.

Happy to hear other view on what to do about this.

Here's one example where the photo is made circular, or in this case ovals because the starting photos are rectangle. I'll look to increase the options but it took me quite a while to find a way to modify the SVG in this way so I haven't looked into other shapes yet:
![image](https://user-images.githubusercontent.com/89974636/222045419-cb47c69a-d96c-4f42-a9cd-5c71c7c6629f.png)

**Comment by hartenthaler** [comment]
First: Thank you! The oval images are looking great. They would fit perfectly to the new "modern" theme of webtrees. 

Second: I have to think about it.

**Comment by Neriderc** [comment]
One of the main benefits of installing Graphviz is that you don't hit diagram size or memory issues (well, the limits are much higher anyway). If you're making diagrams with 1,000 or more individuals you may hit the error with the Viz.js library used for creating the Graphviz diagram in the browser. If you want a high DPI, you may simply hit the maximum canvas size that your browser can support (16,384 x 16,384 for most browsers, though the limit is actually in total pixels so shorter image could be wider before hitting the limit. Firefox has a slightly higher limit than the other major browsers).

I agree that since we cannot support this through server-side Graphviz, we should dynamically disable this as needed.

**Comment by Neriderc** [comment]
This is done and committed to the main branch. For the size of the photo, I've used the % system used elsewhere, rather than using pixels. The issue is that pixels don't really align to what you expect. The pixels setting for the size in Graphviz are not the same as the image itself. For example, when I inspect the image in the browser diagram when using default settings I see a width of 28px. The photos clearly are wider than this, but I think this is related to the layout of the SVG (SVG images are scalar - they don't have pixels, so the idea of pixels doesn't apply nicely to them - and so doesn't work cleanly with the embedded photos, which are not scalar, but raster - they use pixels).

I've added shapes Oval, Circle, Square, and Rounded rectangle. I'd be interested to know if there are any issues as I did have a little trouble getting it to work how I wanted, but these all work well for me now.
