### ISSUE TITLE
Large Cookies from GVExport are preventing access to webtrees: Size of a request header field exceeds server limit

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#365]
I had a strange problem: see https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/37833-edge-specific-site-size-of-a-request-header-field-exceeds-server-limit#98353

I could not access my test site using the Edge browser anymore. The reason were four very large cookies from GVExport. After deleting them, everything was ok again. Maybe it was a temporary problem based on several test activities. So you can close this issue. But whenever this problem appears again, the reason is documented now.

**Comment by Neriderc** [comment]
Yes I've also seen this before, when trying to set up multiple saves for logged out users. Probably this would not come up for most production users.

From v2.1.17, when logged in no cookies are used. When logged out, only the main settings are saved in a cookie (i.e. what is currently in the form). The different cookie versions are saved in local storage.

The settings currently in the form are best saved as a cookie, because cookies are sent to the server and the settings are loaded server side so that when the page loads the settings are set.

However, we do have a problem here, and it will get worse as we add more settings. Cookies are limited to 4MB total (including the ones webtrees itself sets), for good reason, as these are sent to the server every page load.

At some point we will need a better approach to this. I'm happy to take ideas! It would be ideal to only load the cookie relevant to the current tree, but cookies do not work like that. I experimented with keeping everything in local storage, but this is not accessible to the server and loading settings after the page has loaded with default settings looks janky.

Maybe we can store settings in local storage, but copy them to the cookie with javascript, selecting the correct cookie based on what tree we are in? I'm not sure what is possible. I think we will leave this open and try to refactor this to be more reliable.

**Comment by Neriderc** [comment]
Another idea, apply [bzcompress](https://www.php.net/bzcompress) to compress the data. I quick test using an online tool tells me in decreased the size by 249%. What does that mean? I'm not sure how they calculated that... but it seems to be a reduction of about 75% which would go a long way to preventing this being an issue for most people.

![image](https://user-images.githubusercontent.com/89974636/220042363-b7ce37ec-0a83-4fe5-b43f-cd485bfbe4d0.png)

**Comment by Neriderc** [comment]
Turns out bzcompress is not standard in PHP, but gzcompress is. I've used gzdeflate which has less header data so saves more space.

The real world reduction was only about 40% for me. However, for this issue to come up there would need to be multiple trees that are available to logged out users, and the users would need to have used GVExport in each tree to generate a cookie.

I've closed this for now. If this is raised again, we can look at other options. I believe the javascript option will end up janky. Potentially we could keep one cookie that is used for all trees like we had previously, which while not great is less of an issue as cookies aren't used for logged in users anymore.
