### ISSUE TITLE
La versión 2.17 no permite cerrar menú de configuración

### ISSUE THREAD

**Issue by BernatBanyuls** [Neriderc/GVExport#369]
Saludos, Neriderc! 

Excelente módulo. Lo he actualizado tan pronto como me lo ha advertido webtrees, pero me encuentro con un problema (he visto que hasta ahora nadie lo ha comentado) y te informo para ver qué puedo hacer.
El módulo se instala correctamente (versión 2.17) y no se genera ningún error, pero cuando le pido un gráfico No puedo cerrar el menú de configuración (con el aspa de arriba a la derecha (x)) y, por lo tanto, no me llega a generar ningún gráfico. No puedo hacer nada ni tan siquiera para salir y he de salirme de la página. Sé que con el "aspa" el menú se repliega a la izquierda, pero eso no lo puedo hacer con la nueva versión. Te adjunto unos pantallazos por si te sirve de información complementaria. 

Estoy utilizando la última versión de webtrees y los módulos vesta y alguno más.

![image](https://user-images.githubusercontent.com/103060233/220429602-dc586b6c-4a7e-4202-878e-630d77426dcd.png)

![image](https://user-images.githubusercontent.com/103060233/220429693-2de4ebf4-7455-4191-85de-1db5884f58aa.png)

A pesar de todo, el módulo me parece muy bueno. He reinstalado la versión 2.16 y todo vuelve a funcionar.

**Comment by Neriderc** [comment]
Hi Bernat, sorry to hear you are having this problem.

The first thing to try is a "hard refresh" of the page. Hold shift and click the refresh button in your browser. If your browser has saved some of the code then this may be mismatched with the server and cause issues. This hard refresh should solve that issue.

If you are still having trouble, I suggest you disable the module (you can do this by adding a '.' in the name, common convention is to rename the module 'GVExport.disabled'). Then with the module disabled, go to the control panel. You should be prompted by webtrees to let you know there are settings saved for a module that is no longer installed. Choose the option to delete the settings.

Next, enable the module again and see if the issue is resolved.

If that does not work, then please let me know what the error is that the browser is reporting. To do this, right click anywhere on the page, and choose the option "Inspect". This should open a new panel. Choose the "Console" tab on this panel, and you should see an error in red. It would be great to get a screen shot off this. On this error, at the right hand side, you should see a file name mentioned. It probably ends in ".js" and will be in blue. If you click this, it should open the code to where the issue is. It would be good to see a screen shot of this too.

Hopefully the first steps solve the issue, but if not then the details of the error will help me work out what the problem is. Good luck!

I have copied a Google Translate version in Spanish below for you:

Hola Bernat, siento que estés teniendo este problema.

Lo primero que debe intentar es una "actualización completa" de la página. Mantenga presionada la tecla Mayús y haga clic en el botón Actualizar en su navegador. Si su navegador ha guardado parte del código, es posible que no coincida con el servidor y cause problemas. Esta actualización dura debería resolver ese problema.

Si aún tiene problemas, le sugiero que deshabilite el módulo (puede hacerlo agregando un '.' en el nombre, la convención común es cambiar el nombre del módulo a 'GVExport.disabled'). Luego, con el módulo deshabilitado, vaya al panel de control. Webtrees debería solicitarle que le informe que hay configuraciones guardadas para un módulo que ya no está instalado. Elija la opción para eliminar la configuración.

Luego, habilite el módulo nuevamente y vea si el problema está resuelto.

Si eso no funciona, hágame saber cuál es el error que informa el navegador. Para hacer esto, haga clic derecho en cualquier parte de la página y elija la opción "Inspeccionar". Esto debería abrir un nuevo panel. Elija la pestaña "Consola" en este panel y debería ver un error en rojo. Sería genial obtener una captura de pantalla de esto. En este error, en el lado derecho, debería ver un nombre de archivo mencionado. Probablemente termine en ".js" y estará en azul. Si hace clic aquí, debería abrir el código donde está el problema. Sería bueno ver una captura de pantalla de esto también.

Con suerte, los primeros pasos resolverán el problema, pero si no, los detalles del error me ayudarán a determinar cuál es el problema. ¡Buena suerte!

He copiado una versión de Google Translate en español a continuación para ti

**Comment by BernatBanyuls** [comment]
Saludos, Neriderc!

 

He realizado todos los pasos (incluso he borrado y intaladado de nuevo el módulo), pero lamentablemente sigo con el mismo problema.

 

He ido a la consola y he efectuado algunas capturas. Espero te sirvan, pero si necesitas más datos, díme exactamente qué debo hacer.

 



 



 



 



 



 



 

 



 

Como ves, he ido cogiendo los pantallas a  que me han ofrecido información. Si es otro tipo de capturaa que necesitas, ya me diras.

 

Gracias por todo.

 

 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: Neriderc ***@***.***> 
Enviat: dimarts, 21 de febrer de 2023 20:48
Per a: Neriderc/GVExport ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [Neriderc/GVExport] La versión 2.17 no permite cerrar menú de configuración (Issue #369)

 

Hi Bernat, sorry to hear you are having this problem.

The first thing to try is a "hard refresh" of the page. Hold shift and click the refresh button in your browser. If your browser has saved some of the code then this may be mismatched with the server and cause issues. This hard refresh should solve that issue.

If you are still having trouble, I suggest you disable the module (you can do this by adding a '.' in the name, common convention is to rename the module 'GVExport.disabled'). Then with the module disabled, go to the control panel. You should be prompted by webtrees to let you know there are settings saved for a module that is no longer installed. Choose the option to delete the settings.

Next, enable the module again and see if the issue is resolved.

If that does not work, then please let me know what the error is that the browser is reporting. To do this, right click anywhere on the page, and choose the option "Inspect". This should open a new panel. Choose the "Console" tab on this panel, and you should see an error in red. It would be great to get a screen shot off this. On this error, at the right hand side, you should see a file name mentioned. It probably ends in ".js" and will be in blue. If you click this, it should open the code to where the issue is. It would be good to see a screen shot of this too.

Hopefully the first steps solve the issue, but if not then the details of the error will help me work out what the problem is. Good luck!

I have copied a Google Translate version in Spanish below for you:

Hola Bernat, siento que estés teniendo este problema.

Lo primero que debe intentar es una "actualización completa" de la página. Mantenga presionada la tecla Mayús y haga clic en el botón Actualizar en su navegador. Si su navegador ha guardado parte del código, es posible que no coincida con el servidor y cause problemas. Esta actualización dura debería resolver ese problema.

Si aún tiene problemas, le sugiero que deshabilite el módulo (puede hacerlo agregando un '.' en el nombre, la convención común es cambiar el nombre del módulo a 'GVExport.disabled'). Luego, con el módulo deshabilitado, vaya al panel de control. Webtrees debería solicitarle que le informe que hay configuraciones guardadas para un módulo que ya no está instalado. Elija la opción para eliminar la configuración.

Luego, habilite el módulo nuevamente y vea si el problema está resuelto.

Si eso no funciona, hágame saber cuál es el error que informa el navegador. Para hacer esto, haga clic derecho en cualquier parte de la página y elija la opción "Inspeccionar". Esto debería abrir un nuevo panel. Elija la pestaña "Consola" en este panel y debería ver un error en rojo. Sería genial obtener una captura de pantalla de esto. En este error, en el lado derecho, debería ver un nombre de archivo mencionado. Probablemente termine en ".js" y estará en azul. Si hace clic aquí, debería abrir el código donde está el problema. Sería bueno ver una captura de pantalla de esto también.

Con suerte, los primeros pasos resolverán el problema, pero si no, los detalles del error me ayudarán a determinar cuál es el problema. ¡Buena suerte!

He copiado una versión de Google Translate en español a continuación para ti

**Comment by BernatBanyuls** [comment]
![image](https://user-images.githubusercontent.com/103060233/220585643-25539172-cb2e-4e94-aa69-7e9570f4338b.png)

![image](https://user-images.githubusercontent.com/103060233/220585672-0b0da672-92b9-4e4d-83f0-36fa81b891ff.png)

![image](https://user-images.githubusercontent.com/103060233/220585753-96de070a-c40f-4fc9-b3fe-693a1e959216.png)

![image](https://user-images.githubusercontent.com/103060233/220585812-9eddc870-db5d-4995-93cc-85346855ab2b.png)

![image](https://user-images.githubusercontent.com/103060233/220585869-783428c2-6272-4a3e-84ac-bd30870755f7.png)

![image](https://user-images.githubusercontent.com/103060233/220585915-891ee958-ea6c-4a12-8001-0e392952a7a5.png)

![image](https://user-images.githubusercontent.com/103060233/220585948-51e9d5a4-36df-4fc6-8182-5dcc227c4526.png)

**Comment by BernatBanyuls** [comment]
Perfecto, Neridec! Esperaré a la nueva versión.

Muchas gracias por tu trabajo!

**Comment by Neriderc** [comment]
This is closed now as the code change is complete, but I have not yet bundled a new version. Webtrees will let you know when the new version is released.

Ara està tancat, ja que el canvi de codi s'ha completat, però encara no he inclòs una versió nova. Webtrees us informarà quan es publiqui la nova versió.

**Comment by Neriderc** [comment]
I've released the new version, 2.1.17.1, which is a bug fix release. Hopefully this solves your issue :)

He llançat la nova versió, 2.1.17.1, que és una versió de correcció d'errors. Espero que això resolgui el teu problema :)

**Comment by BernatBanyuls** [comment]
Hola Neriderc!

 

Acabo de instalar la nueva versión y sigo teniendo el mismo problema (cuando uso la lengua catalana).

 

He seguido los pasos que me recomendabas en el primer correo, pero no consiguo solucionarlo. El mensaje que informa de la existencia de una nueva versión en el panel de control ha desaparecido, por lo que entiendo que si he reinstalado la “última versión” correctamente.

 

(*He actualizado página con la tecla de “mayúsculas”

* He desabilitado el módulo y lo he vuelto a habilitar

* He provado en Chrome (utilizo Edge normalmente)

Sigue sin funcionar cuando pulso el aspa (x)

 

Quedo a tu disposción para lo que me pidas.

 

Gracias.

 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: Neriderc ***@***.***> 
Enviat: divendres, 24 de febrer de 2023 9:47
Per a: Neriderc/GVExport ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [Neriderc/GVExport] La versión 2.17 no permite cerrar menú de configuración (Issue #369)

 

I've released the new version, 2.1.17.1, which is a bug fix release. Hopefully this solves your issue :)

He llançat la nova versió, 2.1.17.1, que és una versió de correcció d'errors. Espero que això resolgui el teu problema :)

**Comment by hartenthaler** [comment]
When using 2.1.17.1 and the language "Catalan" I can reproduce that issue (cannot close menu).

**Comment by Neriderc** [comment]
Apologies, I thought this was solved but it is not. I am away from home at the moment, I tested the latest release on my production server but cannot access my development server, and I am only accessing via mobile phone which does not let me see the errors in the console. I will work on this when I get back, which may be 24 to 48 hours away.

Disculpeu, pensava que s'havia solucionat però no ho és. En aquests moments estic fora de casa, he provat l'última versió al meu servidor de producció, però no puc accedir al meu servidor de desenvolupament i només hi accedeixo mitjançant un telèfon mòbil que no et permet veure els errors a la consola. Treballaré en això quan torni, que pot estar entre 24 i 48 hores.

**Comment by Neriderc** [comment]
I'm not sure what happened, but this is now a related but different issue causing the same thing. I have tried to fix this in a code update, it works for me, @hartenthaler could you test the main branch and make sure you don't find any issues?

**Comment by BernatBanyuls** [comment]
Claro que sí. 

 

No comprendo en tu mensaje si tengo que hacer alguna cosa por mi parte o se lo estás pidiendo a Hermann.

 

Si necesitas que haga algunas pruebas en mi ordenador o servidor, pásame el código y lo vamos viendo.   Debe ser una verdadera tontería ya que con los demás idiomas funciona perfectamente.

 

 

 

 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: Neriderc ***@***.***> 
Enviat: diumenge, 26 de febrer de 2023 8:59
Per a: Neriderc/GVExport ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [Neriderc/GVExport] La versión 2.17 no permite cerrar menú de configuración (Issue #369)

 

I'm not sure what happened, but this is now a related but different issue causing the same thing. I have tried to fix this in a code update, it works for me, @hartenthaler <https://github.com/hartenthaler>  could you test the main branch and make sure you don't find any issues?

**Comment by hartenthaler** [comment]
Main branch version is tested. Issue is solved now, no new issues.

**Comment by Neriderc** [comment]
> Main branch version is tested. Issue is solved now, no new issues.

Thanks for testing!


> No comprendo en tu mensaje si tengo que hacer alguna cosa por mi parte o se lo estás pidiendo a Hermann.

Apologies, I was asking Hermann to test. I know that he is very familiar with testing non-released code, and he had also commented here that he could replicate the issue.

Disculpes, estava demanant a Hermann que fes una prova. Sé que està molt familiaritzat amb la prova de codi no publicat, i també havia comentat aquí que podria replicar el problema.

> Deu ser una autèntica tonteria ja que funciona perfectament amb les altres llengües.

The issue was caused by line breaks added in the translation of the long help messages. The original terms did not include the line breaks, and the other translations may not have included them (perhaps others had the issue and did not know how to report it). This was a problem due to the interaction between the code on the server (which handles the translation), and the code on the browser (that shows the message when the user clicks the button). This meant all code on the page stopped working (including the code to show or hide the settings). 

Longer term we will change this system as we now have a better way to communicate between the browser and server, but for now I have added code to remove the line breaks. In website content, they are not used anyway (as special HTML code is used instead). The way I have fixed this should mean it is fixed for all languages, but only for the help messages. In future we will completely change how this works but for now it is more important to get a version out that works for you.

El problema va ser causat per salts de línia afegits a la traducció dels missatges d'ajuda llargs. Els termes originals no incloïen els salts de línia i les altres traduccions potser no els incloïen (potser d'altres tenien el problema i no sabien com informar-lo). Aquest va ser un problema a causa de la interacció entre el codi del servidor (que s'encarrega de la traducció) i el codi del navegador (que mostra el missatge quan l'usuari fa clic al botó). Això significava que tot el codi de la pàgina va deixar de funcionar (inclòs el codi per mostrar o amagar la configuració).

A llarg termini canviarem aquest sistema ja que ara tenim una millor manera de comunicar-nos entre el navegador i el servidor, però de moment he afegit codi per eliminar els salts de línia. Al contingut del lloc web, no s'utilitzen de totes maneres (ja que s'utilitza un codi HTML especial). La manera en què he solucionat això hauria de significar que està arreglat per a tots els idiomes, però només per als missatges d'ajuda. En el futur canviarem completament el funcionament, però de moment és més important tenir una versió que us funcioni.

I will work on getting a new version out for you.

**Comment by BernatBanyuls** [comment]
Perfecto!!!! Excelente trabajo! Ahora todo funciona bien, incluso en catalán!!
