### ISSUE TITLE
Highlite "Toggle advanced settings" 

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#406]
I like the new design very much. If you have unfolded all options then the "buttons" "Toggle advanced settings" are not visible good enough, because there are so many text elements around. Maybe one solution is to make this text a button, but this will disturbe the design. Or to colour this text or to make it bold? The up and down arrows are nice and helpful.

**Comment by Neriderc** [comment]
Just to make sure I understand correctly, is this what you are referring to?
![image](https://user-images.githubusercontent.com/89974636/235281610-a502c987-2376-4288-87e9-0d55002aca25.png)

I thought the blue background would have made it clear it was the end of the section, and so easy to find?

**Comment by hartenthaler** [comment]
Oh. It is a problem of some webtrees themes. It looks very good for all the webtrees standard themes (beside "minimal", what is ok) and for "Rural". It doesn't for "Argon", "Argon Light", "JustLight", and "modern". 

Should I ask JustCarmen to optimize her theme JustLight for GVExport?

![Screenshot (268)](https://user-images.githubusercontent.com/6324175/235295520-d95b57db-2bec-44f5-ac1a-229f305a9c44.png)

**Comment by Neriderc** [comment]
> Should I ask JustCarmen to optimize her theme JustLight for GVExport?

I don't think so. This appears to be a problem across multiple themes, so in the first instance I think we should try to come up with a solution ourselves.

Going back to your initial comment:

> Maybe one solution is to make this text a button, but this will disturb the design. Or to colour this text or to make it bold? The up and down arrows are nice and helpful.

I think without the background colouring, it is not clear that it is may be clickable. The button idea is ok, but you are right, it would not look great.

I think one problem is that we need to respect the theme, so for example we shouldn't do things to overwrite the theme in order to make it look how we want. This could have unintended consequences.

Perhaps one idea is to simply have another way to identify it. For example, we could have a box around the advanced settings - though I feel we have enough boxes within boxes. Another idea is to have a thick line down the left-hand side. I often see this (though I cannot recall a place right now), where the line is also somewhere you can click to close the advanced settings. The issue with this though is that whichever colour we choose for this line, we will want to allow it to be able to fit in a theme, so would want to pick one of the webtrees classes. But then this risks having non-compatible colours in other themes.

Perhaps the answer here is to find a place in webtrees that does something similar, and if it looks ok in these themes then copy the colours? This may mean changing the colours we use, but if we can replicate something from the core webtrees, it's more likely to still work with custom themes. I don't have a suggestion for what area of webtrees to copy, while I can think of places where each of the components are found, I can't think of any that combine them in a similar way.

**Comment by Neriderc** [comment]
One last bonus one for this release.

I have added a check to see if the colour of the advanced settings buttons (which is supposed to be darker) is the same as the colour of the part that is supposed to be lighter. If so, then I take the "primary button" colour and use this instead.

On the themes I tested (Modern, Argon, Minimal) I think this looks ok. Definitely better than before.

Let me know what you think!

**Comment by hartenthaler** [comment]
This works now for all themes beside JustLight.  The toggle "button" is not looking good in both modes of this theme (light and dark). Thank you!

I'm in contact with Carmen, so it is no problem for me to ask her about that issue. Maybe she has a good idea. Shoud I ask her?

**Comment by Neriderc** [comment]
> This works now for all themes beside JustLight. The toggle "button" is not looking good in both modes of this theme (light and dark). Thank you!
> 
> I'm in contact with Carmen, so it is no problem for me to ask her about that issue. Maybe she has a good idea. Shoud I ask her?

No it's fine. The issue is that this theme uses background gradients instead of the background colour setting, so it wasn't picking it up. A little tweak and now the gradient is used and it looks good.
