### ISSUE TITLE
Some parts of the help text are not translated

### ISSUE THREAD

**Issue by Jefferson49** [Neriderc/GVExport#436]
Observed with v2.1.18 and webtrees 2.1.16

The "Show help" tap and a part of the help text is not translated, although the (German) translation is at 100% at https://poeditor.com/

![Show help](https://github.com/Neriderc/GVExport/assets/81484983/86b0bad6-eb31-4fba-90dc-6fd1a7f04471)
![help](https://github.com/Neriderc/GVExport/assets/81484983/a2f91b42-7f4e-462b-be7d-6de247ca520f)

**Comment by Neriderc** [comment]
Argh! Thanks for reporting this! I have made the changes and will publish an updated release ASAP so people aren't updating to one that has these issues.

For now, I have changed the help panel button to say just "Help" instead of "Show help". This is because the term "Show help" was not available in POEditor so we don't have translations for it. I will switch this back to "Show help" in the next version once translations are updated.
