### ISSUE TITLE
One family tree return error when I try to use GVExport

### ISSUE THREAD

**Issue by dust2k** [Neriderc/GVExport#443]
I have two family trees, one is simple one for sampling and another one is real one, after I upgrade to 2.1.18.1 then the simple one is still OK to get graph, but the real family tree report an error:

`Error running GVExport in browser mode:
TypeError: Cannot read properties of null (reading 'value')`

then following content shows "DOT contents"

**Comment by Neriderc** [comment]
Sorry to hear about the issue! If you change which individuals are showing in the tree, does this help?

Often the issue is about a specific person, and something that makes them unique. Since you say it happens on one tree and not another, it makes me think this may be the case. If you can narrow down which person is causing the issue by changing which people show in the diagram, that would be a big help.

**Comment by dust2k** [comment]
Alright, I will give it a try this afternoon, I might try to switch to few members and minimum all linked members to see what's going on.

**Comment by dust2k** [comment]
All individual members have a same problem no matter how to change related members and even only left one, here is the DOT contents:

**`digraph WT_Graph {
ranksep="0.15 equally"
nodesep="0.15"
dpi="72"
mclimit="1"
rankdir="LR"
pagedir="LT"
bgcolor="#eeeeee"
edge [ style=solid, arrowhead=normal arrowtail=none];
node [ shape=plaintext font_size="10" fontname="Arial, Sans, Arial, Sans"];
X213 [ label=<<TABLE COLOR="#606060" BORDER="1" CELLBORDER="0" CELLPADDING="2" CELLSPACING="0" BGCOLOR="#fefefe" TARGET="_blank" HREF="https://jiazu.xxx.com/index.php?route=%2Ftree%2FNo1%2Findividual%2FX213%2Ffangweizhizi"><TR><TD COLSPAN="2" CELLPADDING="2" BGCOLOR="#add8e6" PORT="nam" ></TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT"  TARGET="_BLANK" CELLPADDING="4" PORT="dat"><FONT COLOR="#333333" POINT-SIZE="12">… 之子</FONT> </TD></TR></TABLE>>];
}
}`**

**Comment by dust2k** [comment]
After comparing two family tree's setting I found the problem, **the "Thumbnail images" must set to "Show"!!!** that's the issue, is it a bug? I am not sure or GVExport should be capable for this setting? anyway, my problem is fixed.

**Comment by Neriderc** [comment]
Thanks for finding this issue! It should not be required, this is definitely a bug, but some recent new functionality has not taken into account that the thumbnails can be disabled.

Luckily the fix is pretty simple. I'll try to get a new version out soon, I have it working but just need to do some testing to make sure I didn't break something else by doing this change.
