### ISSUE TITLE
Change default zoom level to always be the same, zoomed in on the starting person and surrounding individuals, regardless of diagram size

### ISSUE THREAD

**Issue by WeT-Klb** [Neriderc/GVExport#456]
If you choose 3 or 4 generations, would it be possible not to reduce the size of the graphic?
It would be nicer if the individual persons were displayed in the same size, but the graphic could be moved accordingly - as in "MyHeritage".
![GVExport with 2 Generations](https://github.com/Neriderc/GVExport/assets/20600342/f49a3d6e-fba4-4b5e-af0c-64f53a1a0e45)
![GVExport with 3 Generations](https://github.com/Neriderc/GVExport/assets/20600342/db52b660-0411-49d1-bd60-3fda73d29c71)
![GVExport with 4 Generations](https://github.com/Neriderc/GVExport/assets/20600342/a2732cff-232c-499c-a5ad-cb90c7f1e8a7)

_Originally posted by @WeT-Klb in https://github.com/Neriderc/GVExport/issues/232#issuecomment-1826286895_

**Comment by WeT-Klb** [comment]
My personal opinion is that the view as in "MyHeritage" would be optimal. For example, you can select a person and then navigate through the whole tree by moving the graphic. Have you ever seen that there?
In my personal opinion, that would be the icing on the cake.

**Comment by Neriderc** [comment]
Because (by definition) GVExport is powered by Graphviz, we don't have the ability to load more of the tree as you scroll around (which I think is what you mean). Instead, we need to generate the whole tree. If you have thousands of individuals, this can take a long time and can also fail because there's a maximum size the browser can display.

The other issue we have had is getting things in the places we want on the tiles. What seems simple such as adding an edit button in the corner, is not simple when you need to feed this through Graphviz.

Basically, this extension was originally designed (at least 12 years ago) to generate printed diagrams using Graphviz. It does this well, in particular handling complex family relationships where others fail (especially others available for webtrees).  The ability to see the output on the website and scroll around was only added in 2021 (not by me), and I have built on this. However, it's still a printed diagram tool at heart.

I think what you're asking for would need a complete rebuild using a different tool (i.e. it would not be GVExport anymore). And given the popularity of MyHeritage and Ancestry, and the fact that no such extension exists for webtrees despite webtrees having many extensions - I'm guessing it's pretty difficult to do.

One day I might attempt something like that, but to be honest I'm not really sure of a good place to start. Webtrees does already include some level of functionality in letting you scroll your family tree, such as the arrow on the right hand side here:
<details>
  <summary>click to show</summary>
 <img src="https://github.com/Neriderc/GVExport/assets/89974636/f4363804-ed78-41c7-bafc-8894b8ed7947">
</details>

I know this is in no way a replacement, but it's similar conceptually.

For GVExport, I'll only look at having the zoom level set to have the tiles show the same size each time.

(sorry for the long reply, I did try to shorten it - yes, it was longer)

**Comment by WeT-Klb** [comment]
I understand that this is very complex. I also intended it more as food for thought.
I would be satisfied if the zoom level would remain the same - i.e. the person box would remain the same size, but the graphic would have to be moved.
Nevertheless, thank you for your efforts.
And, as you said, perhaps you still have a plan to implement this at some point.

**Comment by hartenthaler** [comment]
If you are interested in interactive opening and closing branches in a tree you should try the custom module xtv (see https://github.com/huhwt/huhwt-xtv).

**Comment by WeT-Klb** [comment]
Danke für den Tip - ist aber leider nicht ganz das, was ich suche.
GVExport geht schon in die richtige Richtung - mir würde halt gefallen, wenn man den ganzen Stammbaum erkunden könnte - wie eben in MyHeritage.

**Comment by Neriderc** [comment]
> If you are interested in interactive opening and closing branches in a tree you should try the custom module xtv (see https://github.com/huhwt/huhwt-xtv).

As far as I can tell, this only shows ancestors and descendants, rather than all records.

**Comment by hartenthaler** [comment]
Und was spricht gegen diesen Wunsch den ganzen Stammbaum mit GVExport zu erkunden?

Eine Möglichkeit wäre diverse Startpersonen in GVExport zu definieren, etwa die Spitzenahnen und deren Nachkommen. 

Eine andere Möglichkeit wäre es den ganzen Stammbaum in den Sammelbehälter zu legen und diesen dann mit GVExport anzusehen. Das geht mit dem Erweiterungsmodul cce https://github.com/huhwt/huhwt-cce

Wenn schon cce installiert ist, dann macht es auch Sinn TAM und LIN vom selben Autor zu installieren, da auch diese beiden Module sich sehr gut eignen einen ganzen Stammbaum zu analysieren (mit einer ganz anderen Bedienoberfläche).

**Comment by Neriderc** [comment]
I've just edited the title to make it clearer what is being changed when this goes through the release cycle. It turns out this was very easy to do. I will submit the pull request shortly.

I have some other stuff I'm working on in the hope of having it in the next release, so for the moment I'll hold off on creating a new release, but one the pull request is merged you should be able to use the main branch to get early access to the change (and others). Feel free to ask if you need help with how to do that. Completing the pull request will close this issue but everyone can continue to reply to it.

**Comment by WeT-Klb** [comment]
> Und was spricht gegen diesen Wunsch den ganzen Stammbaum mit GVExport zu erkunden?

Es spricht natürlich nichts gegen den Wunsch. Ich wollte nur sehen, ob es möglich ist. z.B. mich als Person auszuwählen und dann frei durch den ganzen Baum zu navigieren, indem ich die Grafik verschiebe. Mir gefällt einfach die Möglichkeit, die MyHeritage bietet. Dieses Feature fehlt mir persönlich in Webtrees.

**Comment by Neriderc** [comment]
@schuco I think what you have suggested is already covered in #402. I have copied your comment over to make sure we get a nice experience doing this functionality when the time comes.

Currently I have been working on #416, which has been taking some time because of the complexity, and I expect to take a fair bit more time to complete, but it is making progress.

**Comment by schuco** [comment]
After working with the change resulting in a fixed zoom level for some months now (since November 2023), it is my experience, that this change has not been favourable in all cases. Especially when I am displaying a big tree the strong zoom on the last individual added opens a much too narrow scope of the tree. In most cases it is my first action to widen the zoom before I can inspect the result of adding the last individual.
The present approach may be more useful in a top-to-bottom diagram than in left-to-right diagram, which I am maily applying.

**Proposal:**
When a fixed zoom is used the scope should include at least the parent generation and the direct offspring generation.
Maybe a dynamic solution could be useful, where the zoom diaplay a preset proportion of the tree.
