### ISSUE TITLE
Color of link should depend on the type of relation

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#46]
The color of a link should depend on the type of the relation. It is very hard to interpret the diagram in the modes "simple" and "decorated". The color of a link between the spouses and their family should be different from the color of children and their parent family.

**Comment by Neriderc** [comment]
I'm trying to visualise what this might look like. Would this work the same way that "mark not blood-related people in a different colour" works, i.e. if related to a starting person they are one colour, otherwise another? I suspect this isn't what you mean.

So I'm curious how this would work. Say I start with my child. The links to my wife and I would be one colour, but the link to my wife's family would be a different colour to the links to my family? And the link to my wife's father would be a different colour from my wife's mother? That seems confusing.

Do you think you could draw a picture the explains how you think this should work?

**Comment by hartenthaler** [comment]
No, I'm talking only about the color of links = arrows. At the moment all links are black. It would help if they have two different colors.
![Screenshot (174)](https://user-images.githubusercontent.com/6324175/174500969-9f2729ac-5981-4ddd-8980-5ce3adf046e7.png)

**Comment by Neriderc** [comment]
Ok I think I understand now. One colour arrow from the couple to their family, and another colour from their family to their children. Any suggestions for what colours to use?

**Comment by hartenthaler** [comment]
"black and blue" or "dark blue and dark green"?

The colors should be different from the colors already use for the boxes. And they should be more dark than light.

**Comment by Neriderc** [comment]
Ok we can try out those colours.

I think this should be optional, we should add a checkbox in the appearance section that covers this.

**Comment by hartenthaler** [comment]
At the moment GVExport is not using a configuration menu in the control panel. Maybe some of the options in the menu can be relevant to the user, others can be decided maybe by the webtrees admin. To make the colors an option is good. But to offer too many options to the user is not good. There are more options hidden in the code, maybe some of them can be transferred to the control panel and can be changed by the admin.

**Comment by Neriderc** [comment]
Good thinking! All the colours could be configurable in the control panel. 

I'm not sure if any on the panel at the moment eould be better in the control panel. Perhaps DPI and the separation values? Normally you'd set these once and not change them again, and with sensible defaults you may never need to change them.

**Comment by hartenthaler** [comment]
Yes, DPI and space are candidates to be moved to the control panel. Another one is MCLIMIT (number of iterations). All the other ones should be influenceable by the user. I will open a new issue for that.

**Comment by hartenthaler** [comment]
see issue #51

**Comment by Neriderc** [comment]
Great, thanks!

**Comment by hartenthaler** [comment]
The color of the links to the children can change by the status "birth", "adopted", ... There was already a discussion about that, but I could not find it at the moment.

**Comment by Neriderc** [comment]
Just to make sure I've got this right:

- Link from parent to family - black
- Link from family to biological child - dark blue
- Link from family to adopted child - dark green
- Add a checkbox to enable/disable in the Appearance section

I'll leave the configuring of colour and the control panel stuff to #51 and just use this issue for the links.

**Comment by hartenthaler** [comment]
I would say

- Link from _**spouse**_ to family - black
- Link from family to biological child - dark blue _**(all children without status or status = "birth")**_
- Link from family to adopted_**/foster/rada/sealed child**_ - dark green  _**(all children that are not "birth" or without status)**_

**Comment by hartenthaler** [comment]
Perfect! It is a great pleasure to work with you. Greetings from Hiddensee (a very small island in the Baltic Sea).

**Comment by Neriderc** [comment]
With you too! Thanks so much for all the help. I'm in New Zealand, way around the other side of the world!

**Comment by Neriderc** [comment]
Is this what you're thinking?
![image](https://user-images.githubusercontent.com/89974636/189258766-ab19ca77-3b39-4964-8b9c-771aa75ec962.png)

Link from each spouse to family record stays the same. Link from family record to each child is coloured dark blue (biological child) or dark green (non-blood related).

**Comment by hartenthaler** [comment]
This looks very good. You can see the colour, but they are all dark so that the diagram does not get too colourful.

**Comment by Neriderc** [comment]
Great! My plan is to disable it by default. Will be able to change the colours:
![image](https://user-images.githubusercontent.com/89974636/189313297-caa828fd-1457-4dea-b54b-8b7302e49e92.png)

Is there a term that refers to the links between people in a family tree to use instead of "arrows"? Or is "arrows" a good way to refer to these settings?

**Comment by hartenthaler** [comment]
Relationship?
Relationship arrows?

**Comment by Neriderc** [comment]
Yes I think that sounds good. "Relationship arrows" for the category on the left to make it clear what we are talking about, and leave the rest as it is.

I have this all working so when I get a chance I'll change that terminology, add the terms to POEditor, and create the pull request.

In this case I've got with show/hide of the addional options instead of disabling. Partly because it seems to make more sense in this context and partly because a disabled colour picker does not stand out like other disabled fields, so it is hard to see that it is disabled.
