### ISSUE TITLE
size of exported pdf

### ISSUE THREAD

**Issue by arbor95** [Neriderc/GVExport#466]
The size of the exported pdf is very big.
What is the reason?
How to shrink after export?

**Comment by arbor95** [comment]
I am without Graphviz.
Using Combined diagram type.
I can not see a setting for quality. (resolution is 100%, size is 100%, but sure not from the original jpg what is for all my photos 240x320 pixel)

Having a look into the generated pdf: Seems to me as if : The complete block of partners is stored as one image.

**Comment by Neriderc** [comment]
The quality options don't apply if you don't have Graphviz installed on the server, as in this case the output is generated entirely in the browser. And unlike when you have Graphviz on the server, the images you use don't matter as they are not embedded in the document.

There is definitely something funny happening with PDF.

PDF generation uses a JavaScript library to generate the PDF based on a PNG image (basically, it takes the PNG output then feeds this into the PDF creator).

For some reason, if I create a PNG of a large diagram I get a normal file size (for my test diagram  about 7MB), but if I generate a PDF of the same diagram it is 260MB!

I'm not sure of the reason, I'll have to do some digging.

**Comment by Neriderc** [comment]
After a lot of digging and trying out things, in the end the issue was that jsPDF by default doesn't compress the file. It was as simple as setting a setting to compress the file.

I've pushed this into the main branch, so anyone keen can download from that branch and start using this right away (let me know if you need help with this), but please note that the main branch has an updated Graphviz renderer and still has at least one minor display issue, #465. These are the only unreleased changes so far.
