### ISSUE TITLE
minor display issues with boxes

### ISSUE THREAD

**Issue by HerzScheisse** [Neriderc/GVExport#516]
Hi, 

No big issue, but just want to mention this anyway... maybe you hav a fix in mind for this...
If you have boxes with round corners, the bar overlaps the box a bit... 
![2024-11-03 22_56_00-Window](https://github.com/user-attachments/assets/955bff8e-60b8-4b4d-a139-b13b6e46355f)

and the second issue is, if you choose the "combined" type... the boxes dont have round corners...
![2024-11-03 22_56_47-Window](https://github.com/user-attachments/assets/6e131523-9b9d-4624-821e-1a7e5799ff92)

**Comment by Neriderc** [comment]
I think there were reasons for this, some combinations don't play nice together and I don't think I was able to satisfactorily resolve them, but I will have another look and see what I can do.

**Comment by Neriderc** [comment]
I have had another play, and because it's an SVG (and Graphviz doesn't seem to parent things as I'd expect) I haven't been able to resolve this visual issue. If you're using rounded corners, it might be better to use a different indicator of sex than the stripe (e.g. background colour, or the option to show sex in words).

I've marked this as "help wanted" in case anyone else wants to have a go at fixing this.

**Comment by Neriderc** [comment]
I have thought a little bit more about this. My efforts have been focused around trying to get the rounded corners to cut off the sides of the coloured stripe, so the stripe goes up to the edge. This has been difficult for reasons mentioned earlier.

What if we changed the approach, and instead made the stripe shorter, so it does not reach the edge?

Here's a quick mockup I made. I can't promise to make it look exactly like this, but I think we must be able to get close:
![screen shot of rounded rectangle tile from GVExport diagram with coloured stripe across the top that normally indicates sex having been cut short so it only extends as wide as where the curve starts, with a gap between the stripe and the edge](https://github.com/user-attachments/assets/eb02adb8-dff0-4e92-9a7f-ea8379fdde91)

I think this would look better than how it currently looks with the stripe crossing over the side.

**Comment by HerzScheisse** [comment]
yeah this is absolutly fine... great

**Comment by Neriderc** [comment]
> What if we changed the approach, and instead made the stripe shorter, so it does not reach the edge?

I have done this now, the change is in the main branch but not yet in a published release.

> and the second issue is, if you choose the "combined" type... the boxes dont have round corners...

This is a problem with the control we have in Graphviz. The combined view brings components together, but if we try to give them round corners then each piece gets round corners instead of just round corners on the whole combined record. Graphviz doesn't allow us to pick the particular corner to make round. Any attempt to solve it just causes other problems, so rounded corners are not supported in combined mode.
