### ISSUE TITLE
Missing translation in dropdown menus

### ISSUE THREAD

**Issue by TheDutchJewel** [Neriderc/GVExport#71]
I've added the Dutch translation files, but the dropdown menus (for Graph Direction and Abbreviated place names) are not translated by the module:

![afbeelding](https://user-images.githubusercontent.com/46184729/175387365-2b5779b4-0fcc-4d7b-8be2-b80c2cec952a.png)

![afbeelding](https://user-images.githubusercontent.com/46184729/175387670-4268ae3f-1292-48fa-9e54-a0aad7bc1f68.png)

**Comment by Neriderc** [comment]
Thanks for the translation! This bug was noticed by another contributor yesterday when the translation to Spanish was being done. This should be fixed in the master branch now.

Did you want to do the pull request to add the language? I'm happy to do it but if you do it you get credit for your work :)

You can export from the PO Editor site by first going into the language, then clicking Export at the top.

Export both the .po and .mo file. We use the .mo for the translation but I'd like the .po file as well so we have the human readable format in source control in case we need to revert for some reason.

**Comment by TheDutchJewel** [comment]
> Did you want to do the pull request to add the language? I'm happy to do it but if you do it you get credit for your work :)

Thanks for pointing this out, and for the clear explanation of how it works, what is needed and why.

See [pull request #73](https://github.com/Neriderc/GVExport/pull/73).
