### ISSUE TITLE
Check if Graphviz is installed on server

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#76]
If Graphviz is not installed at the server, in the menu the section "Output Settings" should be grayed out (or removed), and ".dot" should be selected fix in that case.

**Comment by Neriderc** [comment]
I've tapped into existing functionality for if the path to GraphViz is not set in the config, this just has DOT as the only option in the list. I've made this change in #77, and also changed the message about GraphViz to only show if GraphViz is not available (and reworded to make it suit the new situation).

I don't want to gray out as I hope to eventually have some options to generate output (other than DOT) client side. In this case we can grow the list of options that show when there's no GraphViz installed.

Happy to reassess if you have a good argument otherwise :)
