### ISSUE TITLE
XREF is displayed using vesta_classic_look_and_feel even when display-option is unchecked

### ISSUE THREAD

**Issue by schuco** [Neriderc/GVExport#91]
I use vesta_classic_look_and_feel, not least to display and make use of the XREF, which can be directly entered into GVExport.

However even when "Show individual ID" (XREF) is unchecked, XREF for individuals is displayed in the diagram. So I can't get diagrams without XREF included, unless deactivating vesta temporarily.

In contrast he corresponding option to include XREF works for families.

Is this a bug in GVExport or is it a problem in the vesta module?

**Comment by Neriderc** [comment]
So we've looked at something related to this before in #31 where the XREF was showing up twice. Your issue is actually quite easy to solve given this. I just need to move the code that removes any existing XREF. Currently I only remove it if I'm adding another, but I can remove it in any case and then add it back only if enabled. In hindsight this should have always been like this but we were trying to solve a different problem so didn't think of it at the time.

I know you're not using the latest version, but it's probably easy for you to solve if you have access to the files of the module.

In the file "functions_dot.php", look for the line `if ($this->settings["show_pid"]) {`. Looking back at the code you're running from the previous repository, this should be on line 645. Don't touch this line, but immediately before this line, add a new line with:

`$name = str_replace(" (" . $pid . ")", "", $name);`

I will look at making the change to this repository, but will first have to work out how to install that set of modules to test :)

**Comment by schuco** [comment]
Thank you very much for your quick replies and the big improvements you have achieved!
Since today I work with wt2.1.6 and GVExport 2.1.4.3!

**Comment by Neriderc** [comment]
Exciting! I will work on getting the vesta modules installed so I can test that this works. I'll put it in the next version :)

**Comment by hartenthaler** [comment]
hmmm... The Vesta module offers the option "show XREF". If you don't like it, don't select it. The GVExport module offers the same option because it makes sense when adding/removing parts of the tree. 

I would not like when GVExport overrides the option of another module (Vesta).

- GVExport=off and Vesta=off => XREF invisible
- GVExport=on and Vesta=off => XREF visible
- GVExport=off and Vesta=on => XREF visible     > you prefer "XREF invisible", but why is GVExport more important than Vesta?
- GVExport=on and Vesta=on => XREF visible (one times)      > this was issue #31

**Comment by hartenthaler** [comment]
@schuco "unless deactivating vesta temporarily"

This is not necessary, only deselect the option "show XREF when showing a name" in the control panel of the Vest module.

**Comment by hartenthaler** [comment]
Because the name of a family is not shown by GVExport the Vesta option regarding showing an XREF is not relevant for showing families in GVExport. So for families, only the setting of the GVExport parameter is relevant.

Maybe it is possible to change the GVExport option from "show XREF" to "hide XREF"? Then it would be possible to implement your use case.

GVExport=hide and Vesta=off => XREF invisible
GVExport=hide not selected and Vesta=off => XREF visible
GVExport=hide and Vesta=on => XREF invisible         > as you prefer
GVExport=hide not selected and Vesta=on => XREF visible (one times)

**Comment by Neriderc** [comment]
> I would not like when GVExport overrides the option of another module (Vesta).

I would argue that Vesta is overiding the option of GVExport. If you have chosen not to show the XREF, but it is shown anyway, is that not Vesta overriding GVExport's option?

I think it makes more sense that our options continue to work as described, rather than trying to implement some change to the options in the case that the XREF is already included. It also makes more sense that users can use the option that's right there in GVExport, rather than having to go to the control panel to disable the option in Vesta then enable it again afterwards.

I think this makes more sense because GVExport provides a handy and accessible option to enable or disable the XREF. And if users want to not include the XREF but retain the option to show the XREF for the rest of the Vesta modules, that is easily done. If users want to always have the XREF show, they can do this by simply selecting this option, which will be remembered.

In your suggested setup, if users don't want XREF to show in output, then they have to go to the control panel and disable it in Vesta _every time_ they want to use GVExport.

One of these is user friendly and allows for all use cases, and the other is (in my opinion) unnecessarily complicated.

**Comment by hartenthaler** [comment]
You are right, that going to the control panel is more complicated (and even not possible for a normal user). But the option in the Vesta module has the approach to "show XREF wherever in webtrees a personal or a family name has to be shown". So if the admin selects this option, it is in my opinion no good style to allow users to override this. But in general it is not a good idea to select this option in Vesta anyways, because it gives the XREF an importance that it should not have, because XREFs are intended to be only internal, temporary IDs. So feel free to implement this as you like.

**Comment by Neriderc** [comment]
I've had a new idea on this. We already know if the XREF is in the name. Therefore, we can automatically enable showing XREF for individuals if we find the XREF in the name - but only as a default. If the user disables it, we would remember it is disabled.

This lets us respect the XREF option while also letting the user override it.

This does raise another question. Currently the family XREF is not added via Vesta as we don't use the name of the family. But we could add a check that looks at if the family XREF is in the name of the family, and if so, enable the option to display the XREF in GVExport (by default, allowing the user to override).

Any thoughts on this?

**Comment by Neriderc** [comment]
I have implemented this as described above (if you have Vesta installed, it will enable show XREF for individuals by default, otherwise it will respect whichever setting you have chosen).

I will leave families as it is for now.

This will be in the next release.

**Comment by hartenthaler** [comment]
Very good idea! I would prefer that the family XREF follows the same logic as for the individuals even if the family name is not shown (as you described it above).

**Comment by Neriderc** [comment]
I don't seem to be able to get the Vesta setting to work.

I have my settings set up as follows:
![image](https://user-images.githubusercontent.com/89974636/181647200-ab1e9b62-7c6b-4c7f-8f8f-d71bb430b357.png)

But the family page does not show the XREF:
![image](https://user-images.githubusercontent.com/89974636/181647325-776f72d0-5d95-4cbc-9f9c-53a3d003523e.png)

What's more, I suspect there's an issue in the module. Both options submit the same value for the same option:
![image](https://user-images.githubusercontent.com/89974636/181647828-07081d35-9e89-4ae8-95a5-a13d77e5370d.png)

So the module wouldn't be able to tell which option you picked? I actually can't enable one without the other. If I select one and save, then when the page reloads, both are selected. It even says "individual" in the description under the families one.

Do you have the same issue?

**Comment by hartenthaler** [comment]
Yes, you are right. There is an issue in the Vesta module. Should I report it or will you do it?

**Comment by Neriderc** [comment]
I'll do this. I haven't used the Vesta modules before so I just wanted to make sure I didn't mess up the installation, or have some other quirk of my setup causing it. Thanks for confirming, I'll go and create an issue for it now.
