### ISSUE TITLE
Replace XREF in list of start and stop persons

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#93]
The start and stop list of persons uses a very compact list of XREFs to define those persons. But this user interface has two disadvantages
- the user has to know and remember the XREF of all relevant persons when he likes to modify the lists of start or stop persons
- XREFs are intended to be only internal IDs and not to be used in the user interface (the GEDCOM standard mentions this explicitly and allows an application to change the XREFs whenever an application likes to do this).

webtrees does not use the XREF in the user interface (it is only visible if the Vesta module option is set; it is visible in the browser address). So my suggestion is to replace the lists of XREF with lists of names in the user interface (of course still using the XREFs internally in GVExport).

**Comment by Neriderc** [comment]
Ideally, we'd have a sweet selection box, like the one we have now that let's you select a starting individual, but it should let you choose multiple. Doing this manually is probably a fair bit of work, do you know if webtrees has another built in (like the current selection box) that let's you select multiple users?

In the likely case it doesn't, what would you imagine this looking like from a user perspective? We don't have a lot of space, and I doubt you're  thinking of listing full names in a tiny existing XREF box. Are you thinking some sort of list? I'm just having trouble thinking how this would look, especially if you had 100 starting individuals. Are you thinking some sort of "list box"? We'd also need a way to remove any added by mistake, and to clear everything. And how do we handle the case where multiple people have the exact same name?

**Comment by schuco** [comment]
I know about the past debate in the webtrees forum to discontinue the display of XREF from version 2.0 on.  I have to respect this decision made in the past. 
But still it is my personal opinion that this decision has been a matter of principle (not storing data in webtrees because it has no information on the genealogy ; also XREF has no meaning in other trees) rather than a matter of practical reasons.
The existence of the vesta module may indicate that more users of webtrees still think like me.
When you order from an internet shop it is much faster to enter the article code directly (if you know it) than to search and select each article by name. In this example the article number has the same theoretical disadvantage as an XREF, it is not a permanent characteristic of the object and its meaningless in other shops. But I would prefer shops having this option.

I like and use XRFEF since PhpGedview as it has some advantages for my style of working. I mention two examples:

- merging individuals is a mess if you try to find out which one of the long list of "Johann Schulte" as in my pedigree you should select for merging. Some of these "Johanns" not even have a birth date. For me it seems much easier directly selecting by XREF, as it was implemented in webtrees before 2.0, rather than use a special module to prepare merging or search in the bottom line, where XREF is hidden in a link.
- With GVExport I have set up lots of diagrams using multiple starting persons entering their XREFs directly. This is very easy when you take these from a preview where XREFs are shown. I refer to my Johann Schulte example above to claim, that this would be much more complicated if have to select every candidate by name, one after the other.

My points regarding future development of GVExport:

1. I recall that using and easily entering XREF directly has been a main principle and procedure  of GVExport from the beginning.
2. I repeat that "alea jacta est" for XREF in webtrees and as long as vesta modules exist and are properly updated I can live with that.
3. I also admit that it is not easy to exclude a single special XREF from a long list in the selection field, as you may no more be able to remember, which individual it represents. To solve this problem an addon to translate XREFs to individual's names might help.
4. Finally I have to admit that the majority of webtree users not working with XREF should have an easy way to work with GXExport. And maybe an easy solution without exploding the options-box can be found.
5. But I hope, that the easy way of entering XREF directly is maintained in GVExport at least as an option.

**Comment by hartenthaler** [comment]
@schuco 
webtrees is still allowing you to enter in a person selection field to enter the XREF instead of the name in order to select a person. But finally, it shows you the person and a link to the person and not the XREF. This is in my opinion an exemplary user interface. Fast and precise if you know the XREF, easy if you know only parts of a person's name. So, in my opinion, your points 1 to 5 can be fulfilled.

@Neriderc "We'd also need a way to remove any added by mistake, and to clear everything. "
This is why I suggested at the beginning of our discussion to use the clippings cart to manage persons. The clippings cart can show a list of persons, it allows you to delete a person and add more persons, to clear everything. But ok it is an additional step and more complex than the existing user interface in GVExport. So I suggest keeping GVExport as simple as possible otherwise the advantage of the build-in function instead of using the clippings cart function is not there anymore.

I have to think about a way how it could be possible to manage a list of persons in a compact way.

**Comment by schuco** [comment]
@hartenthaler "webtrees is still allowing you to enter in a person selection field to enter the XREF instead of the name in order to select a person. "
I did not know about that. Very helpful to decode the selection list indeed. Thank you for the hint

**Comment by Neriderc** [comment]
I have some vague ideas about how it could work, having a list with details much like when you select a person (name, photo, X button to remove).  But given I can't find anything built in to webtrees that gives us the nice person selection input in a way that lets you select multiple people, it's likely a lot of work. This is especially true as it needs to be able to pull the details of the person in real time, which currently we rely on the built in person selector to do for us. That means AJAX style requests to the server, which I don't think are implemented for anything in GVExport at the moment.

I think for the moment we can leave this on our backlog with the understanding it won't be looked at any time soon, and when we revisit in the future we may find either it's no longer needed because of other changes we've made, or that webtrees has implemented changes that make it easier to do. Or maybe we'll run out of other things to do and have time to do it all manually 🙂.

**Comment by hartenthaler** [comment]
@Neriderc great summary! Fine.

**Comment by Neriderc** [comment]
I had a brainwave of how to approach this. I have dug into how the webtrees dropdown works and managed to get something working. It would be good to have some input on this and see if it works ok for someone else (it's a little hacky because we tap into the data that the webtrees dropdown requests).

@hartenthaler could you try out pull request #216 and see what you think? And see if you find any issues?
The main thing i don't like is that the results still show records that are selected. I haven't attempted to solve this yet, it might be possible by editing the generated results but I can't guarantee this.

@schuco sorry I'm not sure how you can test this out, github doesn't seem to let you download the code of a pull request before it's merged, and I'm not quite ready to merge this into the main code at the moment. It would require some familiarity with comand lines and "git" (the version control tool that gives github it's name). Here's a screen shot instead:
![image](https://user-images.githubusercontent.com/89974636/191633992-caf8afcc-ddf1-4874-84c6-e307fc1fdc1d.png)

**Comment by hartenthaler** [comment]
Hey, that is great! It looks very very good. I have tested using several webtrees themes (still the "modern" theme has a problem).
It makes this module again a very modern webtrees module.

I had some problems that the autorefresh of the diagram is not working as expected, but I assume that this is because I'm travelling on a train and the Internet is not perfect.

> The main thing i don't like is that the results still show records that are selected.

I'm sorry, I do not understand that. What is the point you do not like?

**Comment by Neriderc** [comment]
> I had some problems that the autorefresh of the diagram is not working as expected, but I assume that this is because I'm travelling on a train and the Internet is not perfect.

I've had this problem quite often while developing it, so it may not be because of your internet. It was working fine for me in this version but at times when I had issues often it would resolve itself without changing any code. I'll have to keep testing and see if I can make the auto-update more reliable.

> > The main thing i don't like is that the results still show records that are selected.
> 
> I'm sorry, I do not understand that. What is the point you do not like?

For example, when I search for "Joseph Bloggs" and select him, he is added to the list. Then I click to add another, and there is Joseph Bloggs at the top of the list of new records to add. I would prefer if records already added did not appear in the search, since they can't be added a second time.

**Comment by Neriderc** [comment]
I've pushed an updated version that should more reliably auto-update. It will also more nicely handle the reset (will load up the xref in the URL instead of being blank).

For the second issue of only showing records that are not already selected, I will think on it a bit more to see if I think of something good. I have an idea of how to do it in a more basic way, but I want to think on it a bit more to see if I can think of something better.

One unintended change of this new system is that it now loads the XREFs from last time you were using GVExport. This means that if you go to an individual's page and then go to GVExport, it no longer loads that user as the starting individual. Is this what we want? I think I would prefer to be able to come from an individuals page and have them be what shows. But this presents a bit of a technical problem in that we don't know the difference between this and a reset, since the xref is in the URL regardless.

Perhaps if the xref in the URL is not part of our list and we had just one selected, then replace it. But if there were multiple then add to the list?

**Comment by schuco** [comment]
1. I also observe that persons already selected are wrongly included in the search list.
2. It is true that I am not familar with git and github. I am happy to be able to use the master version. Regarding the solution to replace the XREF in the search lists I admit the solution is much more informative than the line with XREF-codes. I assume that when you have selected to display XREF these will be shown together with the names in the new list. So people like me, who prefere to work with XREF more than with names (I have lots of duplicate Johanns in the families of my tree), still can use XREF. The other issue to be guaranteed with the new list is, that you can include 20 and more people there without making the selection list or the options menue unreadable. I have produced several diagrams using many starting persons, e.g. when the diagram was to show  relations between family lines having common ancestors many generations ago excluding other lines. In these cases I had set max generations 1 for ancestors and descendants. The list of starting persons became quite long then.

**Comment by Neriderc** [comment]
> Regarding the solution to replace the XREF in the search lists I admit the solution is much more informative than the line with XREF-codes. I assume that when you have selected to display XREF these will be shown together with the names in the new list. So people like me, who prefere to work with XREF more than with names (I have lots of duplicate Johanns in the families of my tree), still can use XREF. 

This does not happen based on the GVExport setting. I am using the same request that the search box makes to webtrees to generate this, so it shows the exact same as the search result, which is (mostly) not in my control. However, unlike with the GVExport option for xref, I suspect if you have the xref option enabled in the vesta modules then this will show in this search box regardless of what the setting is set to in GVExport (though I have not tested it). 

> The other issue to be guaranteed with the new list is, that you can include 20 and more people there without making the selection list or the options menu unreadable. I have produced several diagrams using many starting persons, e.g. when the diagram was to show  relations between family lines having common ancestors many generations ago excluding other lines. In these cases I had set max generations 1 for ancestors and descendants. The list of starting persons became quite long then.

It works with lots of records (in theory, no practical limit). I've tested with a few dozen. It of course takes a lot more space, but it's also a lot easier to see who is include (and remove them) than a long list of xrefs where only a few fit in the input field. This is doubly true for invalid xrefs, which are quite easy to spot in this new format.

**Comment by schuco** [comment]
@Neriderc ` I suspect if you have the xref option enabled in the vesta modules then this will show in this search box regardless of what the setting is set to in GVExport`
This would be o.k. for me.
So altogether I would like and prefere the new solution

**Comment by schuco** [comment]
@Neriderc `One unintended change of this new system is that it now loads the XREFs from last time you were using GVExport. This means that if you go to an individual's page and then go to GVExport, it no longer loads that user as the starting individual. Is this what we want? I think I would prefer to be able to come from an individuals page and have them be what shows.`
As I remember the classic version retained the persons in the second line with the aggregated selected persons. Going to the page with a new person and returning to GVE this person was added to the list. For me this is a favorable solution as I mostly build up diagrams stepwise. It should be possible however to delete the last person from the list if it is not wanted. To start from the scratch can be done by a reset.

**Comment by Neriderc** [comment]
> As I remember the classic version retained the persons in the second line with the aggregated selected persons. Going to the page with a new person and returning to GVE this person was added to the list. 

Effectively yes this is how it worked. However, it's a bit weird in that it pulls the xrefs from two places (the person select and the field with a list of xrefs), and if the person in the person select is not added to the list then it is not saved - and if it _is_ added to the list then GVExport calculates this person twice.

My suggestion is to roughly emulate how this works currently:
> Perhaps if the xref in the URL is not part of our list and we had just one selected, then replace it. But if there were multiple then add to the list?

Currently if you have just selected the one person in the person select, then if you go to a person's page then come to GVExport, the person select is set to the person whose page you have just come from (or the default individual if you haven't come from an individual's page). So I've suggested in the new system if you have just one individual selected, then we would clear them and load the new individual - I feel this is less confusing to a new user who might be confused as to how they ended up with two disparate parts of a tree if we simply added to the list. I can easily see someone ending up with many individuals in their list by accident.

However, if someone has multiple individuals in their list, then it's more likely they would want to be adding to the list, or at least would be more likely to understand how the list works with multiple individuals so we would add the individual to the list.

> For me this is a favorable solution as I mostly build up diagrams stepwise. It should be possible however to delete the last person from the list if it is not wanted. To start from the scratch can be done by a reset.

Note that there is also the option of using the webtrees clippings cart to build up the individuals you want to include (but you need to add all records you want, the ancestor/descendant/sibling/spouse/etc settings are not used in this case).

**Comment by schuco** [comment]
@Neriderc ```Perhaps if the xref in the URL is not part of our list and we had just one selected, then replace it. But if there were multiple then add to the list?```
In my practice there are generally two modes to work with GVE:
1. Displaying just the family of the selected starting person, discarding previously selected persons.
2. aggregating persons to a list of reference persons

Could not be there an option how to proceed? E.g. with the starting option according no. 1.

**Comment by Neriderc** [comment]
> Could not be there an option how to proceed? E.g. with the starting option according no. 1.

Yes this is probably the best option. But I am a little concerned about replacing the list. This could easily catch new users off-guard, causing them to lose the list of individuals they have built. I would prefer this option only replaces the list if there is only a single individual in it (less damage in the case this is not what the user wanted). This could be the default setting. Most new users will start with just a single starting record, and in the case of adding more it is easy enough to remove the others from the list. We could have three settings but I'm not sure an option to replace is particularly helpful if the default is set up this way. Perhaps an option to "clear all" would be good, as a quick way to clear the list without resetting other settings.

Let's say we have just the two options, the default one as I describe and then we could have an option such as "Always add the (?) to the list of starting individuals". I'm not sure what to call "(?)" as saying "xref in the URL" is too technical, but this can be fed in from different places. E.g. if you come via an individuals page, this xref will be fed to GVExport. But if you come via the home page you'll get the default individual. If you come via a family page, you get what appears to be the husband/first partner's xref. I'm not sure what a succinct but descriptive way to describe this option would be.

**Comment by hartenthaler** [comment]
> Perhaps if the xref in the URL is not part of our list and we had just one selected, then replace it. But if there were multiple then add to the list?

I would prefer exactly that.

If you use GVExport in mode 1 of @schuco, i.e. showing always the family of one person: whenever I call GVExport from an individual page and there is only a single individual in the collected list of starting persons I would prefer to see the family of this individual. This would replace the previous person on the starting list with the new individual.

If there are already several persons on the starting list, I would assume to be in mode 2 of @schuco. Then I would prefer to add the new individual to the existing list of starting persons.

I would not need an additional option in the GUI.

**Comment by schuco** [comment]
I am trying to understand the difference between getting the status of "single individual in the collected list of starting persons " or "already several individuals in the collected list".
In both cases you would have had to press the "Add to list"-button before. So pressing that Add-button did express the users goal to accumulate individual's in the starting list even for the first single entry.
The problem arising from adding the first (single) individual is, as I understand, that `then GVExport calculates this person twice.` But is this a big problem when you get the same diagram again? The second seemingly unproductive cycle was used to start the accumulating phase.
So as @hartenthaler mentioned my previously proposed mode-options are not really necessary. 

Instead an option could be offered after the first individual has been entered to the list by the Add-button. By that further selected individuals would be automatically added without pressing the Add-button.
As long as I  could enter many xref-codes into the list in one step, such an automated accumulation mode seems not to be urgently needed. But I can't yet imagine if and how this would work when a name list replaces the selection field.

**Comment by Neriderc** [comment]
> I am trying to understand the difference between getting the status of "single individual in the collected list of starting persons " or "already several individuals in the collected list". In both cases you would have had to press the "Add to list"-button before.

This is not necessarily true. If no saved xref exists, the webtrees-provided one is automatically loaded. This will be the case 100% of the time for a new user using GVE for the first time.

> The problem arising from adding the first (single) individual is, as I understand, that `then GVExport calculates this person twice.

This is a "behind the scenes" inefficiency and is not as big of a problem as may have made it out to be. It simply means loading the diagram takes slightly longer than it could. In this new version, this duplication no longer happens anyway, because we only load from the list of xrefs - the person select box is now blank most of the time.

> Instead an option could be offered after the first individual has been entered to the list by the Add-button. By that further selected individuals would be automatically added without pressing the Add-button. 

The problem with this is we would need an option to disable it. Might as well just add an option, it would be easier to implement.

> As long as I could enter many xref-codes into the list in one step, such an automated accumulation mode seems not to be urgently needed. But I can't yet imagine if and how this would work when a name list replaces the selection field.

This may need more thought. Currently you could search for one xref but you wouldn't be able to load many.

One option is to keep the text box that lists xrefs (move it to advanced secrion). Then if any change is made in this box, clear and reload our list of individuals. all the functionality to do this already exists, so it should be pretty straightforward to do and should fulfil this need for you.


I think there are a lot of options of how to approach how we load the xref from the url. I suspect we won't know what we want until we try something, give it a go for a while, and see what we do/don't like.

I propose for the first cut we:
- add to the list if there are multiple records in the list
- replace the record if there is only one
- no options for this at this stage
- add the ability to directly edit the xref list and have this reflect in our visual list displayed
- add a button to clear all records (without having to click reset, which clears the other settings).

This can be our aim for 2.1.13 (there is lots in 2.1.12 already, I'd like to have this released in the next few days).

After this is done I'll close this issue. We can use the new system like this for a while, and create new issues for any ideas for refinement.

**Comment by Neriderc** [comment]
I have made the above changes and have merged the code into the main branch.

@schuco you should now be able to download the code from the main branch and test out this new system for yourself. It has only been implemented as above (without any options). Give it a try, and if you find that an option in regards to how the URL xref is treated would make life a lot easier for you, open a new issue as we can discuss it.

I know you like to deal directly with XREFs, this has been moved to the advanced section.

**Comment by schuco** [comment]
@Neriderc  `you should now be able to download the code from the main branch and test out this new system for yourself. It has only been implemented as above (without any options). Give it a try,`

I tried but got an error. Maybe my php-settings are too restrictive. I would have to wait for my son to change this.
```
Undefined variable: url …/modules_v4/GVExport/resources/views/page.phtml:60
#0 …/modules_v4/GVExport/resources/views/page.phtml(60): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/View.php(183): include('/var/www/vhosts...')
#2 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#3 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#4 …/app/Http/ViewResponseTrait.php(50): view()
#5 …/modules_v4/GVExport/module.php(242): Fisharebest\Webtrees\Module\AbstractModule->viewResponse()
#6 …/app/Http/RequestHandlers/ModuleAction.php(85): vendor\WebtreesModules\gvexport\GVExport->getChartAction()
#7 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#9 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#11 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#13 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#15 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#18 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#19 …/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#21 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#23 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#25 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#27 …/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher->handle()
#28 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#29 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#30 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#31 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#33 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#35 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#37 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#39 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#41 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#43 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#45 …/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#47 …/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#49 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#51 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#52 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#53 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#54 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#56 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#58 …/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#60 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#62 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#64 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#65 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#67 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#68 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#69 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#70 {main}
```

**Comment by Neriderc** [comment]
I don't think it uses anything that would be restricted. Though there's nothing that stands out as being a potential problem. This is possibly because you're using a different version of PHP than I am. I'll look at testing on PHP7.4 and see if I get the error.

The other thing is that this may be related to how I get the URL. Perhaps your URL structure is different and that's causing issues. When you go to the page of an individual, what does the URL look like? Is it something like https://[yourdomain].com/tree/[treename]/indiviudal/[xref]/[person name]? That's how mine is structured. Is yours different?

**Comment by Neriderc** [comment]
@schuco I have tested with pretty URLs disabled and it didn't work (though I didn't get the same error as you), so maybe you're not using pretty URLs and the error may show differently with a different PHP version.

Anyway, I've found a nicer way to get the URL I need for loading the data for the list, so I have updated this in the main branch. Could you re-download from the main branch and give it another go?

**Comment by hartenthaler** [comment]
For me the latest development  version works perfect for the list of the start persons. Much better than everything before. It would be great to see now the stop persons list in the same way.

I observed a new behavior in how using webtrees: I'm starting more often directly using GVExport as my main navigation tool in my trees instead of using the build in tools. And very often I use now the download of a png image in GVExport instead of producing a screen shot using other functions in webtrees when I have to send a image to relatives of me showing how we are related for example. Thank you very much!

**Comment by schuco** [comment]
It works fine with the "nicer way".
In general:
Like @hartenthaler mentioned, the new behavior is a big improvement. I will generally use it .

Congratulation to offer such an easy way to build up a tree and also to display the list of starting persons so clearly instead of cryptic xrefs.

As you left the list of xrefs in the advanced options I can use this in special cases.

**Comment by Neriderc** [comment]
I'm happy to hear it's working! As you continue to use it, open new issues as you think of changes you'd like. I'm confident we will want to make further adjustments as we get familiar with the new system.

**Comment by Neriderc** [comment]
That's great to hear!

> it accumulates starting persons by click and activating GVE there again

In the latest release there is a small change to how this works, to bring it in line with my original plans. I was finding it was adding to the list even when there was only one existing record in the list, when the plan was to replace it in this case as our first test so see how we liked it. So I've fixed this (hopefully) in the latest release, but you may find it's not working quite how you would like now. We can still consider an option to always add to the list, if that's what you'd prefer.
