### ISSUE TITLE
Start with the tree shown initially

### ISSUE THREAD

**Issue by hartenthaler** [Neriderc/GVExport#99]
Start with the tree shown, not an empty diagram space, when opening GVExport. In my opinion, the user interface would be better to see already something when opening GVExport instead of the need to click on "Update" before you can see the diagram.

**Comment by Neriderc** [comment]
I agree this would be great, and probably wouldn't be too hard. Only, I worry about the default settings. Generating a diagram with 5 generations of ancestors and 5 generations of descendants is really quite time consuming (if you have a large family tree). I think perhaps we would need to change those defaults so that a user's first experience is not of waiting a really long time :laughing:. 

Perhaps also change the settings on who to include to only include relatives. That should give a manageable number of records for a first load on default settings (if there are saves settings then we'd use those instead).

Thoughts?

**Comment by hartenthaler** [comment]
Good point! Default of max level one or two generations should be ok as a starting point. And using only relatives is ok, too.

**Comment by Neriderc** [comment]
Done!

I've changed defaults for ancestors to 2 and 2, and now the diagram is rendered on page load.
